POSTGRES_USER: ENC[AES256_GCM,data:xFhtSno=,iv:2gU+RrE+mbO8Ihzd3srSHJ7RzMB/eLtJCJxFoXqIhGE=,tag:wc9eAuCpkznoxSmSZYLVaA==,type:str]
POSTGRES_PASSWORD: ENC[AES256_GCM,data:XngdxVZAgqu44lC6Zl8VSBxUoFy2M4ucD1CotosAdQ0=,iv:RHfRmyhLZNIzUpR0TZrFssOjX3f+2zZ90jO9PrC8X2s=,tag:MtUq9P0wNtaD9gsy9egkuw==,type:str]
POSTGRES_DB: ENC[AES256_GCM,data:a6lc6tY=,iv:sc9eCiHsoE0s1pmsXk4og1WWyrkynAtEmdsjf0eEb1s=,tag:SDPAP7DT33c28z3FnScYAg==,type:str]
sops:
  age:
    - recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNHFvWmJ3NWVHQ0JZaDh0
        bVhMc3ArSW9aVzE5L3hJRlN0M1MxOEFNRFY4Ckpsb2R4cG02OHl5NmNzNVJLQWpw
        a3EvaGxDa1hHK1lMbEpFUmlTMEJMNEEKLS0tIGpkSWNSUzhacWk1YUpKenVzdm5F
        d0ZaaHl3d25GWEtkMm5zS093MCtxQmcKMCLRNmO+94LwIEbn2UUPnrPrdSfPQAOM
        epiZufTAhAdhQxZJ4IZ9q7EPeWx4fIJdSUXIt7aoGkQ4MOPCFgX6vg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-05T13:15:25Z"
  mac: ENC[AES256_GCM,data:Y+Cgb2jxPhLk68vvt/0GZaPd5t0eGhlheoG1p6otOlPUMi01HXp6dsiYODUsjjBp2SrbMtDMmrteDuRXr5rSyxcc13QFcoU+1uklHkp2rv5/ffaKbl/ypkGSvqapzhVqch2dlm9hjd+7IE0Y6wEqM9c63L0axo5En9hNXcHyMT0=,iv:4Kq0N3Lr6IZwb1Og1AsViWgoCZoZQTHyjYb4rWPMDig=,tag:H/Z17oJH2LyAxMmk7Atppg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
