UMAMI_BASE_URL: ENC[AES256_GCM,data:/R90DirWpxzfl76mdf4mBQLlEVDG0l4MGQ==,iv:QXnnsdKgCbWEdldYdk/0EAFbptF+eRIhdfHN7l06XsA=,tag:gx+7sQ4LScZfivG/laB4Sg==,type:str]
UMAMI_WEBSITE_ID: ENC[AES256_GCM,data:5tRFFN6DauerX7GUNRTTUmtkmx49OQXcGIU8kXMfQ/xxPCka,iv:/CEfuIyaebGWYI1XN73lqgF6g7LYCWkQohqZTGIefR8=,tag:N+zJg2iQ1j+i2ZSF0jGLAA==,type:str]
UMAMI_WEBSITE_HOSTNAME: ENC[AES256_GCM,data:3JmZ0VQA8ICXhSE=,iv:dbQvPexSGrDdmL5cnJME8P0APOXuBYWUW22nCWcXrWY=,tag:mTYwbCT0wlhoKnTvA8fiHA==,type:str]
sops:
    age:
        - recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmQkZON0g4blR6UEpSSHJr
            QTEyMzRtbGdaMDJWRy95ZTcxQ2U1UDhUS3hVCnN6UDI3M0o2dFhtOXMzcjlCSzYx
            OHlwbmYzRGxjT1hiNlRvbDVpVmZNTG8KLS0tIGc2OGtGb091MlI5UDBUdENVWTJl
            cXo2V2NMcmpsQlVvVnVETHZQOEltR1UKsk6/HrZnlAmPGrnQWiynQ2HuFrzliTOW
            3DeFZhSmaAg45My0Exm2/OVVFz+e5L+MFROAE2K+cPlhIOXaWGjdNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-26T17:30:10Z"
    mac: ENC[AES256_GCM,data:OrMR7kwBZMSnkyVrUoxdX5xOH+pMyTdh22MljFPNeil8ISS9/ATCmLND57dtEY6fX8oKOp3km2f708h45UYOMT9T14tii233T6GmzEzOkBAnFFqfYehFe+Pq557mYymX7vl0Rv6slXNrEt53piczWlz01ya0dLb0b1W1JTmcEhM=,iv:exJsvaDQQK6vx+wqwxXgvC7t2WQ6UnJqOr280RZkyoI=,tag:j2tD5xm7eXIZe80kNj2EmA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
