GITSYNC_USERNAME: ENC[AES256_GCM,data:j6rCNcDC1Hw=,iv:f0dYi9bqzp48W8M5stqHJnalX4wL4wDogE9tocuwjhk=,tag:qPnkFJdQh+W4JjuiebM2xg==,type:str]
GITSYNC_PASSWORD: ENC[AES256_GCM,data:o7uGYHwD7N/eXGzWloT4jalCJuKyt9kSoYfq0+GtFm2qEX+c4ygLn7SXzSqtaUTT6pNAyrJI7iarupXcRWi7F2iCnbrsZyNO9iMp5VV03ndsEmaW9xzf6NeOBuAZ,iv:7drUbhpSbxCcbZ2be3Nt3t54iAJ+xO0fgCBQh0TsLIA=,tag:FhzV1FHq+rc47byg2xjcVA==,type:str]
sops:
  age:
    - recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1a0tVZ2ZCR3FERDJYOGt2
        Z1BzS0RXaW9yOWpNZWo2anZIU2t6OTgrNlZRCmVJMUMreGQwQWxJZUcxRkMwWGkw
        eW9BWWR2VjJ4bE1nTnc5b1RYTnNuTlEKLS0tIDNGdzNwTjdJL0NLRWZyOVVqL2pK
        bFYvQkVkemRSdmhKSnAvcFQ3eEx6dXcKMMPrgzDdNbUBj0h0J9W4T3tbBEuIP1cx
        EGnzO1bKoiD4AceQeIwbbdgZCITDrcXKeJjTUC4b3hJfMhA7meMCOg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T05:30:19Z"
  mac: ENC[AES256_GCM,data:GVuVF+Iirn/Pruu8n7fpRnjdk6/nLyA+VVJ4PvudB9pp7MdIMAzS57QRdJS7G61EtUhybBuEUVvKS2XyXtVTi2uSlYJN7GT8sUPfxXVaKk4GPncAUKUjl7/Y1ogLJpuxvLpoVMELecdhDaH3JnwKHI+Ytxj8TWvc/e5eLA5E2Cc=,iv:XAX14hvynDqEGvhkbxvBbtpfXaIyOq7ksayKNZq5t6U=,tag:MQFSyiwShpoRgXr/ynzJ3A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
