kind: StatefulSet
name: atuin-postgres
replicaCount: 1
containers:
  - name: postgres
    repository: postgres
    tag: 18.1-alpine
    port: 5432
    livenessProbeScheme: tcp
    envFrom:
      - secretRef:
          name: atuin-postgres
    volumeMounts:
      - name: data
        mountPath: /var/lib/postgresql
volumes:
  - name: data
    hostPath:
      path: /opt/atuin/db
service:
  port: 5432
