kind: Deployment
name: atuin
replicaCount: 1
containers:
  - name: atuin
    repository: ghcr.io/atuinsh/atuin
    tag: v18.10.0
    port: 8888
    env:
      - name: ATUIN_HOST
        value: "0.0.0.0"
      - name: ATUIN_PORT
        value: "8888"
      - name: ATUIN_OPEN_REGISTRATION
        value: "false"
    envFrom:
      - secretRef:
          name: atuin
    args: ["server", "start"]
service:
  port: 8888
  nodePort: 30085
