kind: Deployment
name: cpubench
replicaCount: 1
containers:
  - name: cpubench
    repository: ghcr.io/kahnwong/cpubench
    tag: "f905662"
    port: 3000
    env:
      - name: LISTEN_ADDR
        value: ":3000"
    envFrom:
      - secretRef:
          name: cpubench
    volumeMounts:
      - name: data
        mountPath: /data
    livenessProbeScheme: tcp
volumes:
  - name: data
    hostPath:
      path: /opt/cpubench/data
service:
  port: 3000
  nodePort: 30080
imagePullSecrets:
  - name: ghcr-cfg
