kind: StatefulSet
name: paperless-ngx-valkey
replicaCount: 1
containers:
  - name: valkey
    repository: valkey/valkey
    tag: 9.0.1
    port: 6379
    livenessProbeScheme: tcp
    volumeMounts:
      - name: data
        mountPath: /data
volumes:
  - name: data
    hostPath:
      path: /opt/paperless-ngx/valkey
service:
  port: 6379
