name: stirling-pdf
containers:
  - name: stirling-pdf
    repository: docker.stirlingpdf.com/stirlingtools/stirling-pdf
    tag: 2.4.3-ultra-lite
    port: 8080
    env:
      - name: LANGS
        value: en_US
service:
  port: 8080
  nodePort: 30040
