kind: StatefulSet
name: supersecretmessage-vault
replicaCount: 1
containers:
  - name: vault
    repository: hashicorp/vault
    tag: 1.21.3
    port: 8200
    securityContext:
      capabilities:
        add:
          - IPC_LOCK
    envFrom:
      - secretRef:
          name: supersecretmessage-vault
    resources:
      limits:
        cpu: 999m
        memory: 512Mi
      requests:
        cpu: 20m
        memory: 128Mi
service:
  port: 8200
