kind: Deployment
name: weather-api
replicaCount: 1
containers:
  - name: weather-api
    repository: ghcr.io/kahnwong/weather-api
    tag: "d01a5a1"
    port: 3000
    env:
      - name: LISTEN_ADDR
        value: ":3000"
    envFrom:
      - secretRef:
          name: weather-api
    livenessProbeScheme: tcp
service:
  port: 3000
  nodePort: 30078
