storage:
    type: ENC[AES256_GCM,data:eapNz+RS,iv:QLNfK+HZAeWP+2Yzkw3AV07rRqBMQh7EN7T7T9Eebb8=,tag:XT5w1dh5aSBXXLeMa5olKA==,type:str]
    path: ENC[AES256_GCM,data:8Fy3fo09ZPaBAaWrpA==,iv:PImC7MVIG0q52ox4e8WkI7y5shg6Rf+g9dm0StEQtzQ=,tag:rpd6XmTMNNLQWTMayJgFaQ==,type:str]
alerting:
    discord:
        webhook-url: ENC[AES256_GCM,data:0/vrjZ0qIxzOEXRHUpclZOYhRkOKgN+F0/9avSdm3QOuoVYt+89x3R6JJ3hd+ysl6IyZmD95U4B1eceWjfRtqctPkGq8LfREOi0wxSNUggp59B44u0J/gfPAuJpOwalLw0p9Tt9FQFjqM5hn4n+91dWBhNsH6cR2jQ==,iv:UMg+pAZ2q+hxwvOXpfxskoEz5jf556Bo9xujV56s9J8=,tag:8NhY8upzK9mwSOPhKh/Dog==,type:str]
endpoints:
    - ENC[AES256_GCM,data:vnI6hbX/DeNCdklBe1zFFRkc,iv:Dw9AGF0RUHOhJwC8ZTVRgaH7DxS4ruINsfUNPrMhZFQ=,tag:/16S1VgWxUI41cPhEOnWYg==,type:comment]
    - name: ENC[AES256_GCM,data:/B32UY5P3dd5pmQ=,iv:My8eQHeDz+23A7Ccv6UsSp31GfIOzu349peH7gfYCb8=,tag:7tnkqpmiBfpl0JUI2/9+IQ==,type:str]
      group: ENC[AES256_GCM,data:Lhc8UVA=,iv:P2ImpLqsUHjG6m3Ir5v1WVkvxulLOotIpkX1OtPC2ac=,tag:eJgl+WKxNejz8QkHc+O4Bw==,type:str]
      url: ENC[AES256_GCM,data:CJ6THc71plrSnNRbRMjy2lVCPVU=,iv:zGXrkyXXaqLM0oyeNC3Y3o2uR+/9TfP6SWj+50UfE6k=,tag:UvghxLSRNBtpPzgPlKE6iQ==,type:str]
      interval: ENC[AES256_GCM,data:RTk=,iv:PFwiwDu9tlguyjEXL8TnvLDmnwySyGObkwtWEiz5m8E=,tag:GZlsmPNhvCcuWf1bNyLEyQ==,type:str]
      conditions:
        - ENC[AES256_GCM,data:4z9bIJr44RL67+3hcOyd,iv:f8gWkQuldPkcaJfd2a8e9lerXP9fFCk3yDEy7pwZnYk=,tag:cPjJTLo1x6IAgR+f6N8X6g==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:pfYFUn0SrQ==,iv:XiIWSYCLXZs+1dlF1WtfjRBUVhnixBs6f0cJJCaM+QI=,tag:wbaEKKEq514SlXRugOXrzg==,type:str]
          description: ENC[AES256_GCM,data:myfwaRfl2OU4QAMB6LhnJTol,iv:hHdpIQPiVpNnlXY/MvRki8qj6047Hp8p7O6W1b1ctvw=,tag:KrDbB7sdlVqutOmxRahSPQ==,type:str]
          send-on-resolved: ENC[AES256_GCM,data:xM4jUw==,iv:srg7mDO1USCuc1yxUtOERu6DKyePyzFyx+spe1J0ltc=,tag:NMRh1AyePcCC25DM5DHQZg==,type:bool]
    - name: ENC[AES256_GCM,data:Z7wDoQ==,iv:ufu/XSaqbTXiW/hc1EC3eXXOLjs1PDUb6VwkelgT7mY=,tag:OYbIyNDi5lWx3t+kiAlgGA==,type:str]
      group: ENC[AES256_GCM,data:OhsYQRo=,iv:+E59QBVICXKz3o2MkvX+e3JVAHxPFZTTJzyu2RDD7Us=,tag:aG6IoJlXHhS+28ugamU9Ww==,type:str]
      url: ENC[AES256_GCM,data:Akwq+kD/CCklV+h7hbDj5SvDvsJFsBHt9g==,iv:r+3fQxl/lP5Am0TIu0TIB6U9W6520RVY5X8J7+Zq6pc=,tag:apkPp+S6kV91lpfuL+/YIg==,type:str]
      interval: ENC[AES256_GCM,data:s8o=,iv:V4E/mUA3m18OBPXBLNnqIOp51QliCYmjL+xfdhZKHak=,tag:9WR1f6uVx9ELmIg+k6VRMw==,type:str]
      conditions:
        - ENC[AES256_GCM,data:+g+WM2/7hDO+YIyidXrs,iv:mawQbelmZXaxb1++N7/RQYcenzGJJoFP2cAQ46X3pKI=,tag:yGM9/eTLyLazggtFCBZViA==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:J0kCaWYrTQ==,iv:ylwmAz0vYbZVOFAZ5i4aCrvAuhj6z4HvP2hbZbzkLV4=,tag:DOa4QRZEOVJMet/6aYkkPA==,type:str]
          description: ENC[AES256_GCM,data:tg2jJUQhY+NmKfwh02OClXhK,iv:W7DtN6AOM3ZCrXuX8gnc3UAUYjGvNm5l5MBF358enwI=,tag:/nSYyaL/mAToQNPBIqN9sQ==,type:str]
          send-on-resolved: ENC[AES256_GCM,data:3liBZw==,iv:dh19qnu/HjkYw5nFthLEvnUAEfAZLAZPWdZn2ZZD3PM=,tag:m7mK/xRNIO44XR3lKmpqSQ==,type:bool]
    - name: ENC[AES256_GCM,data:WVuUREpKCQU=,iv:9et+HtvZceLrdPU9vsNCbWpnuBVn17J1s31jeP94dVo=,tag:sQdUKcHduk6TL/51BYm11A==,type:str]
      group: ENC[AES256_GCM,data:MkReCzI=,iv:1ZFE4pFKSJAKZ2M97N+zyv5vXKbS6ToQplX1z1GhRcc=,tag:pYmFDx+FolciG4OK/y4EUw==,type:str]
      url: ENC[AES256_GCM,data:xN4On/UAJND5TMxVXHXAUiRon5NpNgh3yV3H510=,iv:5794KlUcSROS2xj2AS3ZlwMBeFDzJCZhqueqaJlz0pw=,tag:cqlsX85ot0EH0nN4H+Tkiw==,type:str]
      interval: ENC[AES256_GCM,data:/Cs=,iv:Romx94WqQ/b7dxaUkAVN2EITPLBYvRuE/5ZPxIFONNk=,tag:4gKx4aDXdCozWBNt1VHoxQ==,type:str]
      conditions:
        - ENC[AES256_GCM,data:C4H1wVB2DxdYIJp2wPG2,iv:ST2+/7GGJGfEqNNRrJY5IBYA90iL9BzQAQibmjZ+UXc=,tag:nDXA9GnplSLK41GhFlchbw==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:Js8aAQBsKA==,iv:dL+Jljepsib4glY1/smE0X0JcBB56um3X0qvfa9kvp0=,tag:OGYE/x8RecJeCAv7P8rzAw==,type:str]
          description: ENC[AES256_GCM,data:oL2wuEPA2kGqQkVOM5JmVnkn,iv:DdZeauC0OUz84Ee7/d7t+wMZWGA0ftUqFAuXYf1gG9I=,tag:HNvWi2dTvEehCvQDf2W32w==,type:str]
          send-on-resolved: ENC[AES256_GCM,data:ZQv/oQ==,iv:zuMhIz1DfSgk0uZNdbrTGN/jcEfKPvIELnRyQdON9RI=,tag:WkHr3+/cVJNO3oVyOPaOzA==,type:bool]
sops:
    age:
        - recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZXpIQzlEQUl2dmNDUUlo
            cWEvSG1lZTZBOTZxYkU2cWZjdEtJQXlxOGwwCnkrcUZ4WnRNR0grMzBSUGdNbjEv
            T0xyV1V4RXJRU2I0N1pzZ2JDU0Izbm8KLS0tIDJKeC9yYzJqVG1NbjFOa3BOQ2l3
            MVhjZGlSNjF1NmtMeEJ1RnVTQzQ1YnMKR0ziCpJxC+vQyfNlcktUsyqgYpwqY1BH
            r8/dBlu7EvYOmSkydlN+DZ7Gw6KU1Kb1gCj/oECzkDsprD8RDAG99Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-07T04:01:38Z"
    mac: ENC[AES256_GCM,data:JkAdBkAW6XlzK8cMixO+m4al5nnp4ZY6ADeVwXNRK0tNDTPn9iIktGK4x/E0Cr/9gqTABEiafYalxDLf6s8AT/DmZybjiQM3GVsV4MVWaCFLkRM4/svhtTme4Gl0xsT3vfr+l2D0le7q2vsOf2LXJbpEL6pKGNbeIBs/qGFOkRU=,iv:EBvOjrzDoABtSwEh3RXo4CqzZz458EH0fSwSu3zFWLc=,tag:bNtdK8si5UYaRgWhKBm5QA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
