storage:
    type: ENC[AES256_GCM,data:eapNz+RS,iv:QLNfK+HZAeWP+2Yzkw3AV07rRqBMQh7EN7T7T9Eebb8=,tag:XT5w1dh5aSBXXLeMa5olKA==,type:str]
    path: ENC[AES256_GCM,data:8Fy3fo09ZPaBAaWrpA==,iv:PImC7MVIG0q52ox4e8WkI7y5shg6Rf+g9dm0StEQtzQ=,tag:rpd6XmTMNNLQWTMayJgFaQ==,type:str]
alerting:
    discord:
        webhook-url: ENC[AES256_GCM,data:0/vrjZ0qIxzOEXRHUpclZOYhRkOKgN+F0/9avSdm3QOuoVYt+89x3R6JJ3hd+ysl6IyZmD95U4B1eceWjfRtqctPkGq8LfREOi0wxSNUggp59B44u0J/gfPAuJpOwalLw0p9Tt9FQFjqM5hn4n+91dWBhNsH6cR2jQ==,iv:UMg+pAZ2q+hxwvOXpfxskoEz5jf556Bo9xujV56s9J8=,tag:8NhY8upzK9mwSOPhKh/Dog==,type:str]
endpoints:
    - ENC[AES256_GCM,data:vnI6hbX/DeNCdklBe1zFFRkc,iv:Dw9AGF0RUHOhJwC8ZTVRgaH7DxS4ruINsfUNPrMhZFQ=,tag:/16S1VgWxUI41cPhEOnWYg==,type:comment]
    - name: ENC[AES256_GCM,data:/B32UY5P3dd5pmQ=,iv:My8eQHeDz+23A7Ccv6UsSp31GfIOzu349peH7gfYCb8=,tag:7tnkqpmiBfpl0JUI2/9+IQ==,type:str]
      group: ENC[AES256_GCM,data:MkReCzI=,iv:1ZFE4pFKSJAKZ2M97N+zyv5vXKbS6ToQplX1z1GhRcc=,tag:pYmFDx+FolciG4OK/y4EUw==,type:str]
      url: ENC[AES256_GCM,data:CJ6THc71plrSnNRbRMjy2lVCPVU=,iv:zGXrkyXXaqLM0oyeNC3Y3o2uR+/9TfP6SWj+50UfE6k=,tag:UvghxLSRNBtpPzgPlKE6iQ==,type:str]
      interval: ENC[AES256_GCM,data:/Cs=,iv:Romx94WqQ/b7dxaUkAVN2EITPLBYvRuE/5ZPxIFONNk=,tag:4gKx4aDXdCozWBNt1VHoxQ==,type:str]
      conditions:
        - ENC[AES256_GCM,data:C4H1wVB2DxdYIJp2wPG2,iv:ST2+/7GGJGfEqNNRrJY5IBYA90iL9BzQAQibmjZ+UXc=,tag:nDXA9GnplSLK41GhFlchbw==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:Js8aAQBsKA==,iv:dL+Jljepsib4glY1/smE0X0JcBB56um3X0qvfa9kvp0=,tag:OGYE/x8RecJeCAv7P8rzAw==,type:str]
          description: ENC[AES256_GCM,data:oL2wuEPA2kGqQkVOM5JmVnkn,iv:DdZeauC0OUz84Ee7/d7t+wMZWGA0ftUqFAuXYf1gG9I=,tag:HNvWi2dTvEehCvQDf2W32w==,type:str]
          send-on-resolved: ENC[AES256_GCM,data:ZQv/oQ==,iv:zuMhIz1DfSgk0uZNdbrTGN/jcEfKPvIELnRyQdON9RI=,tag:WkHr3+/cVJNO3oVyOPaOzA==,type:bool]
    - name: ENC[AES256_GCM,data:Z7wDoQ==,iv:ufu/XSaqbTXiW/hc1EC3eXXOLjs1PDUb6VwkelgT7mY=,tag:OYbIyNDi5lWx3t+kiAlgGA==,type:str]
      group: ENC[AES256_GCM,data:MkReCzI=,iv:1ZFE4pFKSJAKZ2M97N+zyv5vXKbS6ToQplX1z1GhRcc=,tag:pYmFDx+FolciG4OK/y4EUw==,type:str]
      url: ENC[AES256_GCM,data:Akwq+kD/CCklV+h7hbDj5SvDvsJFsBHt9g==,iv:r+3fQxl/lP5Am0TIu0TIB6U9W6520RVY5X8J7+Zq6pc=,tag:apkPp+S6kV91lpfuL+/YIg==,type:str]
      interval: ENC[AES256_GCM,data:/Cs=,iv:Romx94WqQ/b7dxaUkAVN2EITPLBYvRuE/5ZPxIFONNk=,tag:4gKx4aDXdCozWBNt1VHoxQ==,type:str]
      conditions:
        - ENC[AES256_GCM,data:C4H1wVB2DxdYIJp2wPG2,iv:ST2+/7GGJGfEqNNRrJY5IBYA90iL9BzQAQibmjZ+UXc=,tag:nDXA9GnplSLK41GhFlchbw==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:Js8aAQBsKA==,iv:dL+Jljepsib4glY1/smE0X0JcBB56um3X0qvfa9kvp0=,tag:OGYE/x8RecJeCAv7P8rzAw==,type:str]
          description: ENC[AES256_GCM,data:oL2wuEPA2kGqQkVOM5JmVnkn,iv:DdZeauC0OUz84Ee7/d7t+wMZWGA0ftUqFAuXYf1gG9I=,tag:HNvWi2dTvEehCvQDf2W32w==,type:str]
          send-on-resolved: ENC[AES256_GCM,data:ZQv/oQ==,iv:zuMhIz1DfSgk0uZNdbrTGN/jcEfKPvIELnRyQdON9RI=,tag:WkHr3+/cVJNO3oVyOPaOzA==,type:bool]
    - name: ENC[AES256_GCM,data:WVuUREpKCQU=,iv:9et+HtvZceLrdPU9vsNCbWpnuBVn17J1s31jeP94dVo=,tag:sQdUKcHduk6TL/51BYm11A==,type:str]
      group: ENC[AES256_GCM,data:MkReCzI=,iv:1ZFE4pFKSJAKZ2M97N+zyv5vXKbS6ToQplX1z1GhRcc=,tag:pYmFDx+FolciG4OK/y4EUw==,type:str]
      url: ENC[AES256_GCM,data:xN4On/UAJND5TMxVXHXAUiRon5NpNgh3yV3H510=,iv:5794KlUcSROS2xj2AS3ZlwMBeFDzJCZhqueqaJlz0pw=,tag:cqlsX85ot0EH0nN4H+Tkiw==,type:str]
      interval: ENC[AES256_GCM,data:/Cs=,iv:Romx94WqQ/b7dxaUkAVN2EITPLBYvRuE/5ZPxIFONNk=,tag:4gKx4aDXdCozWBNt1VHoxQ==,type:str]
      conditions:
        - ENC[AES256_GCM,data:C4H1wVB2DxdYIJp2wPG2,iv:ST2+/7GGJGfEqNNRrJY5IBYA90iL9BzQAQibmjZ+UXc=,tag:nDXA9GnplSLK41GhFlchbw==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:Js8aAQBsKA==,iv:dL+Jljepsib4glY1/smE0X0JcBB56um3X0qvfa9kvp0=,tag:OGYE/x8RecJeCAv7P8rzAw==,type:str]
          description: ENC[AES256_GCM,data:oL2wuEPA2kGqQkVOM5JmVnkn,iv:DdZeauC0OUz84Ee7/d7t+wMZWGA0ftUqFAuXYf1gG9I=,tag:HNvWi2dTvEehCvQDf2W32w==,type:str]
          send-on-resolved: ENC[AES256_GCM,data:ZQv/oQ==,iv:zuMhIz1DfSgk0uZNdbrTGN/jcEfKPvIELnRyQdON9RI=,tag:WkHr3+/cVJNO3oVyOPaOzA==,type:bool]
    - name: ENC[AES256_GCM,data:vi0nz4Y=,iv:PSbWLsppYCEzDUgw6StYl5vfgzlYGCEbMZER4aqtYUI=,tag:T1szyKkGhXdT6ZtazkwQuw==,type:str]
      group: ENC[AES256_GCM,data:MkReCzI=,iv:1ZFE4pFKSJAKZ2M97N+zyv5vXKbS6ToQplX1z1GhRcc=,tag:pYmFDx+FolciG4OK/y4EUw==,type:str]
      url: ENC[AES256_GCM,data:wthwSzd3UxyW7w9eceQ4A1duHRJVgKbUMXQ=,iv:i5HyH4fytHzCDPOr2AjrK632I610ZbvRvi8qa8VbyUY=,tag:KQH61uHO7VeJOUjIh0eSJA==,type:str]
      interval: ENC[AES256_GCM,data:/Cs=,iv:Romx94WqQ/b7dxaUkAVN2EITPLBYvRuE/5ZPxIFONNk=,tag:4gKx4aDXdCozWBNt1VHoxQ==,type:str]
      conditions:
        - ENC[AES256_GCM,data:C4H1wVB2DxdYIJp2wPG2,iv:ST2+/7GGJGfEqNNRrJY5IBYA90iL9BzQAQibmjZ+UXc=,tag:nDXA9GnplSLK41GhFlchbw==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:Js8aAQBsKA==,iv:dL+Jljepsib4glY1/smE0X0JcBB56um3X0qvfa9kvp0=,tag:OGYE/x8RecJeCAv7P8rzAw==,type:str]
          description: ENC[AES256_GCM,data:oL2wuEPA2kGqQkVOM5JmVnkn,iv:DdZeauC0OUz84Ee7/d7t+wMZWGA0ftUqFAuXYf1gG9I=,tag:HNvWi2dTvEehCvQDf2W32w==,type:str]
          send-on-resolved: ENC[AES256_GCM,data:ZQv/oQ==,iv:zuMhIz1DfSgk0uZNdbrTGN/jcEfKPvIELnRyQdON9RI=,tag:WkHr3+/cVJNO3oVyOPaOzA==,type:bool]
    - ENC[AES256_GCM,data:fA4fuAlOKEvWFEvrn8oaRFI=,iv:FOR7IKRK7XsGASwTTXBctEzLwnr1cFiqaqAe4kjgwXQ=,tag:lOLeO8Kr4SaVmZtaiAZMlg==,type:comment]
    - name: ENC[AES256_GCM,data:w9/DuQZ/t58T,iv:v0krceLyR5M1cEwHEaQCvQsaqrHLvA4R/x2oVwZOkZY=,tag:wxPsmdniMgfEUlswQYeBhA==,type:str]
      group: ENC[AES256_GCM,data:MZe1kw==,iv:0flle7U6o3vcMHtRdpT83XHKY6OliCBGYx2gf8fuekY=,tag:2clWnJXuEH3nTFwxdkxFgQ==,type:str]
      url: ENC[AES256_GCM,data:hYE/+AC7C8aj0uzekOem+olvDAG1JSCpl6CfU0di,iv:d0ed+PoYameBJirl+197cWCfM6phGF2taOwR3HhY/RM=,tag:MhA6ID4UoZkyn04Ua8DK7g==,type:str]
      interval: ENC[AES256_GCM,data:/Cs=,iv:Romx94WqQ/b7dxaUkAVN2EITPLBYvRuE/5ZPxIFONNk=,tag:4gKx4aDXdCozWBNt1VHoxQ==,type:str]
      conditions:
        - ENC[AES256_GCM,data:C4H1wVB2DxdYIJp2wPG2,iv:ST2+/7GGJGfEqNNRrJY5IBYA90iL9BzQAQibmjZ+UXc=,tag:nDXA9GnplSLK41GhFlchbw==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:Js8aAQBsKA==,iv:dL+Jljepsib4glY1/smE0X0JcBB56um3X0qvfa9kvp0=,tag:OGYE/x8RecJeCAv7P8rzAw==,type:str]
          description: ENC[AES256_GCM,data:oL2wuEPA2kGqQkVOM5JmVnkn,iv:DdZeauC0OUz84Ee7/d7t+wMZWGA0ftUqFAuXYf1gG9I=,tag:HNvWi2dTvEehCvQDf2W32w==,type:str]
          send-on-resolved: ENC[AES256_GCM,data:ZQv/oQ==,iv:zuMhIz1DfSgk0uZNdbrTGN/jcEfKPvIELnRyQdON9RI=,tag:WkHr3+/cVJNO3oVyOPaOzA==,type:bool]
sops:
    age:
        - recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZXpIQzlEQUl2dmNDUUlo
            cWEvSG1lZTZBOTZxYkU2cWZjdEtJQXlxOGwwCnkrcUZ4WnRNR0grMzBSUGdNbjEv
            T0xyV1V4RXJRU2I0N1pzZ2JDU0Izbm8KLS0tIDJKeC9yYzJqVG1NbjFOa3BOQ2l3
            MVhjZGlSNjF1NmtMeEJ1RnVTQzQ1YnMKR0ziCpJxC+vQyfNlcktUsyqgYpwqY1BH
            r8/dBlu7EvYOmSkydlN+DZ7Gw6KU1Kb1gCj/oECzkDsprD8RDAG99Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-15T07:10:02Z"
    mac: ENC[AES256_GCM,data:p7SelbdZisQa/zDSWvh1vzMYJK6s5IBQZehLd6D6lgqLX2nG55gWb8NDCmMgJYdUB+FZjqjAoSH9CkAj7te83hguAQIeXS7Oa98KCQJHNOdXo6+WKzKIGJf06QDe1rZyk8+sjPYRObTaf97eWE0IyiOOnJYpBw0wvho1QKY7V94=,iv:rd/6Ii6ykxL2Onzid4WORnR8Qa7xtahIk4FzFprfXLw=,tag:f96gSK26v9GEGvxtRdUw3Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
