sso_providers:
    - name: ENC[AES256_GCM,data:O4u7fMXZbPRe,iv:OjsNIntaLvtb4xOVngnXrC59ojICAB2DUz7fXNiVR70=,tag:g8IkXpM7dF23ZS5w8E3M2w==,type:str]
      label: ENC[AES256_GCM,data:e8QNsrbzvdEg,iv:iXZ5gFVGsdB/JpyQ0nts3aFQyxjRX+e0i7ScXm9jZtE=,tag:4Udwj9TiCpKAuzXeYaPi8w==,type:str]
      provider:
        type: ENC[AES256_GCM,data:Qf+JB6Nl,iv:sKxRBpg/e1t+LFwYrNfug0lw6CD2sseZfWrVUJzbXKA=,tag:N0gLfA8r5dI/K0ejoBujYg==,type:str]
        client_id: ENC[AES256_GCM,data:i5VkV3IW7md4ifR0H6PnjegRgbBac1l/rXceJrh8QnqLLhn4Z4AHGQ==,iv:WLg6PCQXNMlEoPzm5uy6HW8zPNkxWytuNU98jBlSgoM=,tag:5LLeOlkMr82E14YGgzs5wA==,type:str]
        client_secret: ENC[AES256_GCM,data:jXMe7q+ulxxhBK9OL7YBhK4mmSXLgX2PTvS4cxgavs+Hhqq1d2/B9CNgydUrbx8mUQ2r/5/KyvzxqEsJ1OUnBDwn81GhLez93WVvMOyGmack9aUzSVKRiyUz/WhOt3CcO6/EXCj4/RsdohOjKzfqY31ZBInJQfnjadOo0MgR8Cs=,iv:6iserKQvTnHXq+yBYyQvwocX15WjdkG6DKLEhRzfkSs=,tag:vZ7sRNQfJCeV2ClkarvpWA==,type:str]
        issuer_url: ENC[AES256_GCM,data:ayUwkPzLQvb3ES90P1c5tbm4kWKHX3lACh475g9NkPBLQ4M72e+EMjn0H8SIo635IsJblkU=,iv:ulZ8w4riAj/6Nbt9IhdarrQoQponKaNR6r7Eakk1pdI=,tag:tX1T3gnVO1Cd/EA4UtBp3A==,type:str]
        scopes:
            - ENC[AES256_GCM,data:W4zrSOQ=,iv:vvq4GVQqYcfgurqsjzIv5THPar1bwu7lTlIz7sFz8i4=,tag:5OQc04/bnqrkuxdc2NDapg==,type:str]
            - ENC[AES256_GCM,data:KHtZ5p/lnQ==,iv:CXdi9TikET4untpyPnfaRJcdKXdSYa1oQChFLgJNhPw=,tag:+I0G7xgtfxq3rC0c7z2rfw==,type:str]
            - ENC[AES256_GCM,data:T6gV9QKbx4ritTXTDXMfW2xgJpUhzvb/,iv:mPpjU41iPXUUbbpb3l7bxT9HnL+suiUExbQ8LhUTm0I=,tag:ARrUJE42N5qRw2+giwvv2g==,type:comment]
external_host: ENC[AES256_GCM,data:RwQEt4OJTxwEfxMid/GAKaWcDco=,iv:iHmtA+uSbKnoEqe0VZUZPIaD+/awAe67MYXPmxOMXg0=,tag:YkUsw71/XPkDecKjyphHjw==,type:str]
recordings:
    enable: ENC[AES256_GCM,data:80hUUg==,iv:uA7IHGH1SZqGRhnJMnH+xUqRVYIqzlvMn5f3GN7QeC0=,tag:nMoC7dGJUhSADtEWJcIRsg==,type:bool]
    path: ENC[AES256_GCM,data:7gMu2c4pDJABGEjWQPGbgg==,iv:LkNVSczmDjeTKaX72pYNUiU1hw3fQ4f9IS4Sbhc0HQo=,tag:WywfHD3tFcpCF4Hq1ztH3Q==,type:str]
database_url: ENC[AES256_GCM,data:NdyFpoZ/sfcEy1exoqaY,iv:NDGjXKPi/y710kJVvRgBrk/J50L3tZNHi3nO4Uj+Ze4=,tag:i8qUe2wfLXYNEzLscETVwA==,type:str]
ssh:
    enable: ENC[AES256_GCM,data:PTUAXA==,iv:7DZdsLtFekG4yr2U7MvYE/zd5u0a/ZsfxZBxuJaPE48=,tag:eLp9iCc6NjI+WMnDgGO3YQ==,type:bool]
    listen: ENC[AES256_GCM,data:loqCxGZlkxT1,iv:lngGBOtJZ8b82GShuSCskOXdY/t8G0aCW3OFpojts9I=,tag:FNhzFnrah2c3pJXMhC00Kw==,type:str]
    external_port: null
    keys: ENC[AES256_GCM,data:xVGuIJLbb8qaExMBO1Y=,iv:C98ugwnvSMgDinnoAyb0qAU4qM1XyW8XZ8CWofkNklM=,tag:ww4z2cG5IIfresXCgTdqBA==,type:str]
    host_key_verification: ENC[AES256_GCM,data:0E+zV0Lq,iv:0mS847BvKANFP2EmlPJ0GW2L0vJowhfBUvMAqqMHu6A=,tag:Yjyibi3HBs98+7Uj9edrwg==,type:str]
    inactivity_timeout: ENC[AES256_GCM,data:Js8=,iv:ZgAkqLzUXHiWvhvbkDbGaQUwO5kkkh7FZIKDUX3QqQE=,tag:f0G20JIf2ja81IFAF6UFow==,type:str]
    keepalive_interval: null
http:
    listen: ENC[AES256_GCM,data:ZlG80/nfr+ID,iv:2h4scZCxccUNovJWMnEnCu256VVLRCBoKCzqzm4EBzk=,tag:BTQuMW/CymCcxuDDEE3+1w==,type:str]
    external_port: ENC[AES256_GCM,data:JZqb,iv:TCWl/y56VnUoY71R5myxufhttkBm78xI8A+evhhmiSw=,tag:r9Ai+BofvF58ZwfEb22mXg==,type:int]
    certificate: ENC[AES256_GCM,data:5fVzNgsZ8+yGtWPHbgmix2npGNLYquoQ0A==,iv:8IQYWTwimkg+vvwjFCdIekkQPNBSoXW/11etL4C9+Xk=,tag:SCaWSR2eFl5YlNM9QoxdYQ==,type:str]
    key: ENC[AES256_GCM,data:rsisk67QtBKhiFMWNrn+HnM=,iv:OBbsDzRNLDnxFqgsS01jnQW0mihjvByLr/ob2SIr99A=,tag:LCKKal+OjnL6vUN9L0kc0g==,type:str]
    trust_x_forwarded_headers: ENC[AES256_GCM,data:/JrfNkA=,iv:DdsDW9M4Ow2n5mjByZiw6zqff6AXsxAzTndxtNd6Zxo=,tag:w3TpuGEhAQ3X7V+M5q5dZw==,type:bool]
    session_max_age: ENC[AES256_GCM,data:OF0e,iv:To+FjlOInyawK1mZ0VCP9QPm1Kq7VAVE46adGz4xCXU=,tag:pUYiZBPc8j3fCi138goaxA==,type:str]
    cookie_max_age: ENC[AES256_GCM,data:ESfY9w==,iv:FDHjoFrtAnQaK1pvo4cUEEmywT4D9DY1suwSySjoZhk=,tag:ZYpxElmWCw0rLeafMV9log==,type:str]
    sni_certificates: []
mysql:
    enable: ENC[AES256_GCM,data:PSHtlg==,iv:6h7j6a45utS1G+R9zQK58EMCBLWBs1FSXJ0yQs3Oy28=,tag:noaV7IjgmAJZ837HQcXiGw==,type:bool]
    listen: ENC[AES256_GCM,data:bfGAnmxi2/7nTQ==,iv:21Lr2k9Kp47R1WpcbNQIpdDM6jvSf7dxborvLhesdp0=,tag:qwAYa2sCfc1CSKG3zH5fhQ==,type:str]
    external_port: null
    certificate: ENC[AES256_GCM,data:QhBmbGi6uaigj6DeaM9XCaUcZkgTTw1ZPg==,iv:IkjxaVqIo1m3pz2MNiRSTlKcBNXMUcL162FxZNS+/kM=,tag:HWxPdssCVDPmLUdW0g4nFQ==,type:str]
    key: ENC[AES256_GCM,data:mc3gCkN/rOG6MCBugfQYD/c=,iv:8ZkxDMhYkuwHwgTMsR+aPxC2ZdSDlqiLh3KxTS7YAw0=,tag:I0isCmS8OIVrM/9SiGpKAQ==,type:str]
postgres:
    enable: ENC[AES256_GCM,data:1To4Dw==,iv:vHW8TCgBWEXUQuA7gyI2yH1EwRq/2e1+Gfgz4/IZCIA=,tag:GqegGohwOfoVcp759Wwtug==,type:bool]
    listen: ENC[AES256_GCM,data:0MJWRXEiixZavA==,iv:xldGpImDOPBS4f3+AtFmMVzpw5RiFHaj3tQUSRyfpys=,tag:WRP7dRMKUwJklyl01qnl5g==,type:str]
    external_port: null
    certificate: ENC[AES256_GCM,data:v1DMil5jM+Iy+P5q8M3ANsBdgMrEcBPKMA==,iv:slnhmpBsjXJM7J+R/HNq1tj+aDjh1amsT+n2nhGBUPQ=,tag:sMnHa7P6YdnUHnZvUiNPIg==,type:str]
    key: ENC[AES256_GCM,data:qVgwjDqhfP4Kn+lYlHE0NGc=,iv:PDpQU2UK9wnIeN0nPgHugMAM3WxwwSvm2BACIaOtr9E=,tag:h0GhSuvT0FXq1lI0gZMmKw==,type:str]
log:
    retention: ENC[AES256_GCM,data:VV69QXA=,iv:6JAufOq89VW6a74MrwkobSK/q3IXDaBsjVj2Qp+MraE=,tag:JraMyVO6Qhvd7oMpN5mDLQ==,type:str]
    send_to: null
sops:
    age:
        - recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmYkE2QUUxek9uRkhkRlk2
            NU55SDhwM28renE5NUN2OVFHOFRFeHhXV3k0CnRPZHRLRlMyZGZ5L2hvU0hKdDNF
            UmR4bk1hZkcyTDlLMkxiZHFyYTc2dW8KLS0tIDMzWDE1ZTRWL1ZvazV2VlFueFZi
            cGRWZldUdTJ6Z0xKRlE3ZzhaK0d1YUEK9Lf9t3eGYqB5dWfneZLbxzJYn+IFFT1H
            MZXorlsqCi5Gmt/8gDRXV6IPX6m6hwqN3tYPSL8ml+CYAWY/O/Dx9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T13:52:19Z"
    mac: ENC[AES256_GCM,data:XkJvVqNhW83y4qY+FPnZyIGp7sdcTVhL+W97O5OEWk0sWBR8wNwlQ7NWlkejvir3lx2p4yB4ci3cQFp+3AzmrLcf/CVVMdOG6SvsHDq6idKJbDC5TWM3pD/F+PdFA/VK57/Ir/odLmbL9sZibwsc+deQAnaI0V/4fM/aocB9zzw=,iv:KhO4OX0PcE/oJlc+7QqPAIPoCNCpcoBTXGO8q+K+oIY=,tag:WUuJUlp1U4VWtwjHujW8jw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
