name: jellyfin
containers:
  - name: jellyfin
    repository: linuxserver/jellyfin
    tag: 10.11.2
    port: 8096
    env:
      - name: PGID
        value: "1000"
      - name: PUID
        value: "1000"
      - name: TZ
        value: Asia/Bangkok
    volumeMounts:
      - name: jellyfin-media
        mountPath: /data/media
      - name: jellyfin-data
        mountPath: /config
      - name: sink
        mountPath: /data/sink
    resources:
      limits:
        cpu: 2
        memory: 2G
volumes:
  - name: jellyfin-media
    persistentVolumeClaim:
      claimName: jellyfin-media-pvc
  - name: jellyfin-data
    persistentVolumeClaim:
      claimName: jellyfin-config-pvc
  - name: sink
    persistentVolumeClaim:
      claimName: jellyfin-sink-pvc
