opencost:
  mcp:
    enabled: false
  customPricing:
    enabled: true
    costModel:
      # https://github.com/opencost/opencost/blob/develop/configs/gcp.json
      # price/month for this config with 1 TB SSD boot disk: 541.32 USD
      description: Modified pricing configuration based on GCE n2-standard-8 asia-southeast-1.
      CPU: 0.038999
      RAM: 0.005226
      storage: 0 # no dynamically-provisioned disk
      # carbonCost: # doesn't work for on-prem
      #   enabled: true
service:
  type: NodePort
  nodePort: 30054
