opencost:
  mcp:
    enabled: false
  customPricing:
    enabled: true
    costModel:
      description: Modified pricing configuration based on GCE n4-standard-8 us-central1.
      CPU: 0.032578
      RAM: 0.003702
service:
  type: NodePort
  nodePort: 30054
