name: 01-1-lunch-ask
schedule: "30 3 * * *" # 10:30 AM Asia/Bangkok
containers:
  - name: 01-1-lunch-ask
    repository: ghcr.io/kahnwong/line-notify
    tag: 9c70e69
    args:
      - "notify"
      - "ถามคนแก่ว่าเที่ยงกินอะไร"
    envFrom:
      - secretRef:
          name: family-alerts
