# don't forget to forward port `32000` on your router
kind: Deployment
name: forgejo
replicaCount: 1
containers:
  - name: forgejo
    repository: codeberg.org/forgejo/forgejo
    tag: 14.0.2
    ports:
      - name: web
        containerPort: 3000
      - name: ssh
        containerPort: 22
    healthcheckPort: 3000
    env:
      - name: USER_UID
        value: "1000"
      - name: USER_GID
        value: "1000"
      - name: FORGEJO__database__DB_TYPE
        value: postgres
      - name: FORGEJO__service__DISABLE_REGISTRATION
        value: "true"
      - name: FORGEJO__server__ROOT_URL
        value: https://git.karnwong.me
      - name: FORGEJO__server__SSH_DOMAIN
        value: git.karnwong.me
      - name: FORGEJO__server__SSH_PORT
        value: "22"
      - name: FORGEJO__server__SSH_LISTEN_PORT
        value: "22"
      - name: FORGEJO__repository__DEFAULT_BRANCH
        value: master
      - name: FORGEJO__security__INSTALL_LOCK
        value: "true"
      - name: FORGEJO__picture__DISABLE_GRAVATAR
        value: "false"
      - name: FORGEJO__actions__ENABLED
        value: "false"
    envFrom:
      - secretRef:
          name: forgejo
    volumeMounts:
      - name: data
        mountPath: /data
volumes:
  - name: data
    hostPath:
      path: /opt/forgejo/data
service:
  # -- these stay here because i'm too lazy to fix helm chart
  port: 3000
  nodePort: 30026
  # -----------------
  ports:
    - name: web
      port: 3000
      targetPort: 3000
      nodePort: 30026
    - name: ssh
      port: 22
      targetPort: 22
      nodePort: 32000
