kind: Deployment
name: ntfy
replicaCount: 1
containers:
  # create admin user via `ntfy user add --role=admin $role`
  - name: ntfy
    repository: binwiederhier/ntfy
    tag: v2.14.0
    port: 80
    args: ["serve", "--cache-file", "/var/cache/ntfy/cache.db"]
    env:
      - name: TZ
        value: UTC
      - name: NTFY_BASE_URL
        value: https://ntfy.karnwong.me
      - name: NTFY_CACHE_FILE
        value: /var/cache/ntfy/cache.db
      - name: NTFY_BEHIND_PROXY
        value: "true"
      - name: NTFY_ATTACHMENT_CACHE_DIR
        value: /var/cache/ntfy/attachments
      - name: NTFY_AUTH_FILE
        value: /opt/ntfy/user.db
      - name: NTFY_ENABLE_LOGIN
        value: "true"
      - name: NTFY_ENABLE_SIGNUP
        value: "false"
      - name: NTFY_VISITOR_SUBSCRIPTION_LIMIT
        value: "3"
      - name: NTFY_VISITOR_REQUEST_LIMIT_BURST
        value: "5"
      - name: NTFY_UPSTREAM_BASE_URL
        value: https://ntfy.sh
    volumeMounts:
      - name: ntfy-cache
        mountPath: /var/cache/ntfy
      - name: ntfy-data
        mountPath: /opt/ntfy
volumes:
  - name: ntfy-cache
    hostPath:
      path: /opt/ntfy/cache
  - name: ntfy-data
    hostPath:
      path: /opt/ntfy/data
service:
  port: 80
  nodePort: 30022
