UPLOAD_LOCATION: ENC[AES256_GCM,data:FFPEK1J8CurR,iv:lG9GNq3lmWXQW53FFQABGcIt3LKORC4lN4Iz9lKIOcI=,tag:9vn+14E0m9cCg79Cn4dc4g==,type:str]
IMMICH_VERSION: ENC[AES256_GCM,data:kk4fTBXIjQ==,iv:CH11Dqdeg53iaL/ktjwFX8lPhNhHFK15ITu2VY13TmU=,tag:I43HQWfKCGnckbhh2vtAvg==,type:str]
#ENC[AES256_GCM,data:ksjNMN/JkYEEhPc5pkNU4ycb1+alAA==,iv:Y4djpeY8PgC/FOOc/brexZfqw1aTESc/ZBM0rU84vpE=,tag:1T8VErYHi/krUuBzU0PAnw==,type:comment]
IMMICH_PORT: ENC[AES256_GCM,data:a7cpWQ==,iv:NAqlJtuZfr7EwBuXx76cHM2gINUngl5TwwwmNtBx9qw=,tag:t0v7/8nG5ICX9CvF6i5mjg==,type:int]
DB_HOSTNAME: ENC[AES256_GCM,data:o1uDuOag2LhXMuuDpvfqfgZOzOoV/0mAXzj6mx2WKbdAL9Y/O5yNoQ==,iv:dU1EnR1H1vy72NTg4ssigVGO/47fDBBLBPPUT8obEPA=,tag:evjaZxLS00uwprPpkAmG7Q==,type:str]
DB_USERNAME: ENC[AES256_GCM,data:+BXk8JCF,iv:fzoTLIAu4mWbS+5o8cKnMwI5fvaLjznGOUu8dKv5hbI=,tag:Z+QdxjzbB5M8nA8ysonEUw==,type:str]
DB_PASSWORD: ENC[AES256_GCM,data:CqOqcrAke5OUzCgi8ugF0BQhWHI23YGdT7P0VYfMcBI=,iv:AX/i1gC1JOuv1h4BjxzK5NX+V6d3Wo0wwOL0MpDVwRw=,tag:QDr+Fq+URv1Qsimid57v3A==,type:str]
DB_DATABASE_NAME: ENC[AES256_GCM,data:3FbCVMSQ,iv:A4AyzxGx3UWBKULapiv/6yodeF/Mn2RsD54lDKJm8/Y=,tag:GUgjGTEKb+ve/USWkFnTfQ==,type:str]
REDIS_HOSTNAME: ENC[AES256_GCM,data:BIPAJ9DD8p4yeyZqvibLE9OpL4wCAMwuK7NZY5/5lkYfgecQgcQ=,iv:hkrSGlLQiGswm15In/F40lNezPvBkSxMERmIph+dGQM=,tag:sg16ecu8OZhlPdrv+mBmHg==,type:str]
TZ: ENC[AES256_GCM,data:nVL0W8rAmZ5RwJqX,iv:duKBZ+X+5OHCkNYafQ7QboWrGCCBom4Qlq3dzRyvv/8=,tag:HZ5fXLMMu/zScis+6vm5ZQ==,type:str]
sops:
  age:
    - recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VWR5ODMxdk9QYUxkNGE2
        Rk9QUEhIQ0hwZ0R6YlVTNHAxZVRXZjR3dDJnCjZwa3B4R3R2Rkl3K0Z1U2d5bXkx
        b1prTjZzdjVJbFZUb2ROY29iNzNkK2sKLS0tIG8vSUxpT2NDRENBRVd6a3FST2Ux
        UFY5K1hNbHZTMDc0LzI1bit6YnA4QUEKwf2pkYtKJnE2t+E/bvZs2gdOAy+hLkUB
        PMlrSNUl1/1q8UPlbzUNE+TUCYjhKnRAJ4bxkRQBoub9nwaEkn0byQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T08:19:27Z"
  mac: ENC[AES256_GCM,data:zv3/8jU6uJ+ZL7DyWHdixfgQ/49uMKXjg6lAKUewk0vAJHbv1qIMJfq5k4iFP08HlBSvP1w2G8cGAA48RHgB8HtHE3pBkCHb3Va7Wxlmi/qs7AyltA2a0JfP15qr8d8gyhTiQ47uti2NVt8o76Itc92Gtqv9gTl8r3Z0Zf9Py4U=,iv:sobT4jGV2eUhf//MkKQMzLEKQKbhYi3TM8JEV+zXAlc=,tag:VzWoEd5SbJ03B3sZu7TTHA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
