UPLOAD_LOCATION: ENC[AES256_GCM,data:FFPEK1J8CurR,iv:lG9GNq3lmWXQW53FFQABGcIt3LKORC4lN4Iz9lKIOcI=,tag:9vn+14E0m9cCg79Cn4dc4g==,type:str]
IMMICH_VERSION: ENC[AES256_GCM,data:kk4fTBXIjQ==,iv:CH11Dqdeg53iaL/ktjwFX8lPhNhHFK15ITu2VY13TmU=,tag:I43HQWfKCGnckbhh2vtAvg==,type:str]
#ENC[AES256_GCM,data:ksjNMN/JkYEEhPc5pkNU4ycb1+alAA==,iv:Y4djpeY8PgC/FOOc/brexZfqw1aTESc/ZBM0rU84vpE=,tag:1T8VErYHi/krUuBzU0PAnw==,type:comment]
IMMICH_PORT: ENC[AES256_GCM,data:5x2Dow==,iv:b2RWo9915oiNXYZfx8N/gU1kU7AAoAbOAQRTt1fZs1E=,tag:wkcjrdTJbONi9Vf0Dh0Ckg==,type:int]
DB_HOSTNAME: ENC[AES256_GCM,data:o1uDuOag2LhXMuuDpvfqfgZOzOoV/0mAXzj6mx2WKbdAL9Y/O5yNoQ==,iv:dU1EnR1H1vy72NTg4ssigVGO/47fDBBLBPPUT8obEPA=,tag:evjaZxLS00uwprPpkAmG7Q==,type:str]
DB_USERNAME: ENC[AES256_GCM,data:+BXk8JCF,iv:fzoTLIAu4mWbS+5o8cKnMwI5fvaLjznGOUu8dKv5hbI=,tag:Z+QdxjzbB5M8nA8ysonEUw==,type:str]
DB_PASSWORD: ENC[AES256_GCM,data:KZIfibieOEVZvd5VQ0k9PXtVB+UDXrBSgAGOT9Z6TmI=,iv:nLvJQTNk/27rGO0On2fcoIkPLyt2AGc+H528bYxB34I=,tag:HpMW7F7ExIaKS6vBgmwBkw==,type:str]
DB_DATABASE_NAME: ENC[AES256_GCM,data:3FbCVMSQ,iv:A4AyzxGx3UWBKULapiv/6yodeF/Mn2RsD54lDKJm8/Y=,tag:GUgjGTEKb+ve/USWkFnTfQ==,type:str]
REDIS_HOSTNAME: ENC[AES256_GCM,data:BIPAJ9DD8p4yeyZqvibLE9OpL4wCAMwuK7NZY5/5lkYfgecQgcQ=,iv:hkrSGlLQiGswm15In/F40lNezPvBkSxMERmIph+dGQM=,tag:sg16ecu8OZhlPdrv+mBmHg==,type:str]
TZ: ENC[AES256_GCM,data:nVL0W8rAmZ5RwJqX,iv:duKBZ+X+5OHCkNYafQ7QboWrGCCBom4Qlq3dzRyvv/8=,tag:HZ5fXLMMu/zScis+6vm5ZQ==,type:str]
sops:
  age:
    - recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VWR5ODMxdk9QYUxkNGE2
        Rk9QUEhIQ0hwZ0R6YlVTNHAxZVRXZjR3dDJnCjZwa3B4R3R2Rkl3K0Z1U2d5bXkx
        b1prTjZzdjVJbFZUb2ROY29iNzNkK2sKLS0tIG8vSUxpT2NDRENBRVd6a3FST2Ux
        UFY5K1hNbHZTMDc0LzI1bit6YnA4QUEKwf2pkYtKJnE2t+E/bvZs2gdOAy+hLkUB
        PMlrSNUl1/1q8UPlbzUNE+TUCYjhKnRAJ4bxkRQBoub9nwaEkn0byQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T08:19:59Z"
  mac: ENC[AES256_GCM,data:dfCIN2wJ6O/CcJQr3VrS553iUKnxW3Gh4qi6O0gDLDgDmG0G5lt7pVc4GN8mpAz+nBD8vy0AI5mAZ8eHUjLYE+YVtJuQK6Oh01zTF25SP8t4yTeEHGF7eHM+dVBqsisJr+JFHCykgpMTodQXEbPcI7IFlSki5KlRDwBGYN7DYWQ=,iv:C56ksUObv6kfhJQ9wCUFF1Nep2VZpCf6iP+MTAYTmZM=,tag:Vwfs6HABmjbSInfG5+jx3A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
