POSTGRES_USER: ENC[AES256_GCM,data:0ChsCFxZ,iv:0rD9utRwxffYgKwV3vC5m9/e2MN/zLAhamdlgYamwdE=,tag:3EDVPfP3CQbJmj5Wv8WLTg==,type:str]
POSTGRES_PASSWORD: ENC[AES256_GCM,data:p8i9R4oDvQ0aK6xZKFnt+zTRuBRdyo3ClW8OIiEg/do=,iv:8smg/o5C660nweVWxdVoeoJHbLfdUVufu9CDAQr+VP0=,tag:reLNukRhqz/Wj4uQHxGpTw==,type:str]
POSTGRES_DB: ENC[AES256_GCM,data:DZ0uOpcc,iv:OKGyTACAJQOXNl5kr09r60QTjhk9RC03GSEleg3tBEg=,tag:egxOsDEY+B9YUbi+RQ1dXw==,type:str]
sops:
  age:
    - recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQUFoLzlkcjFxdnFPMEE4
        UUJWb3BURWxPc1oyZm1JOG9GUUFPZ1VVTTNVClV5cFErTjZTMDgwaU9ScTBaVTho
        ZWZQQStZcFpXL0NYK2pwWXM4Mm9QTDgKLS0tIElwWjJHdmJUZytmaWl2ZGtXS24y
        N3VSbmozQWdzckZrdUNBVWxjc3QySUkKaD2hN3EkJRnkZp0ZnJBht3z325K16KPK
        J8pnjF4Jf64f9/nBbIjXJwTeazpizw3S3HDCuSYByRh1pJVh4IhIwg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T08:19:41Z"
  mac: ENC[AES256_GCM,data:J5L4v7TMOD1ME9siyVPzQvPvW25M4dFs4fs2CnEYx2jvUpsccbEgLK9vNJ8TCTmhONQs+E+emGzdhrbK9GX62AvQVpDNqbKyJ36qACz7vgRKxauaHoV0vpXkArzhDtM/TMSOck09KFJfy4La7sAwWEeQzvKx0PbwroF07mTJNDo=,iv:4X2tu5ZI1KMEymBcXj9s2Tpl0tPQ/2fzI2gaNX3TaUY=,tag:yFRMiLdhBCinId7KbpayYQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
