POSTGRES_USER: ENC[AES256_GCM,data:UOWi+svl,iv:UyXlWAC5zrKHcVcn8pR9Z7r1TDMKIp8cznhJ6HMSBfY=,tag:gP7auoKm7bUv4Z3m7wRUbg==,type:str]
POSTGRES_PASSWORD: ENC[AES256_GCM,data:0ajes/lFRW7SqTirag+Sana7TrEemy4+P32MZqDzvS4=,iv:EWfnq4IrmNQMP3mDcPuQivtQAuYI9772wBsASEwubIo=,tag:UFWrFzcBg1g7L7JXhksGSg==,type:str]
POSTGRES_DB: ENC[AES256_GCM,data:5od+Fwia,iv:ECHNrk2wvs66/7fo1r1++Yng2crgKMNdH8HCm2olC6s=,tag:pJO/wu2ulzZg0jmAuporZA==,type:str]
sops:
  age:
    - recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrOTBRbEZMY1V0VitZSG1p
        UVI4S1NyamVscElYSG9aRWNoVU1xSWtvUkZzCmJSdGh1RmJaRzNjUEZSUHdFNE41
        VEw2RmFNN2M4WHViSDd3SjJjT1BDdzAKLS0tIEV4SVhCZmt3dkpudFV3Y2N3c1ph
        c3RvNW9FMytRRklGUmdmbVlXWFpiNnMKKaTyy9Wh+uANNzgSnSsvMoaYZw0Z+mQs
        QI8AwmTYnPV+YT7lafGoKlE5uZC5kOl0IauoDMdiFRpmMbIXaCaz+g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T07:47:36Z"
  mac: ENC[AES256_GCM,data:YSh+QD4vicVkjOjy30QXPvSc7UVCAUYkd76GY6sKNsiD8S1r1vhwZ9YVCRNIHDrI37zZLoJ6/rzCdinyUkn3ubuKCosA1Til8fhuRKJFkEJiXLLFXSvgaBjBilL2M1FORsULKqa4nnFqSeR580MaWpEYM4bvcz/Ty/uttZLUMhg=,iv:OQC5OAtU+O2r4vpzLV4DA1CB980c+GgW40yrPN+k5eI=,tag:6fSyQ2lI1i2kOB9IM7yHrQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
