NTFY_BASE_URL: ENC[AES256_GCM,data:n4SwuIqH741+H4OZk6ksU5e16KrN3szCSvty+Tw=,iv:FlzQbba8RWShpesvFXJolvc7o5b5JqFPYf/9TJvTvhw=,tag:a/pvXkzlF7tvHzvy1NLQsg==,type:str]
sops:
  age:
    - recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWUZ3OSt1REY3REpxUFNn
        UGZkUndCUFZIT0Iwa01GY3lieENYejc2YkRzCk9RclVCOGZheUFoZUlGa1RNNHpW
        dkRLdEllNjIrYWdHTUJRWWdtSGZXWTAKLS0tICtIWjNSanpraEdBMS9HWVd0YndV
        YmtNdjMrVllKcjZTVENqbk1mUWVaUEEK/d5NY0AbZk8D+WIKT48njyvKlA/+hvhQ
        Q1wxswBrTzsgaBum5gVO50kWY5V4qw+DtSYN6UJtVi5SE1O0NXB7jw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T07:24:44Z"
  mac: ENC[AES256_GCM,data:BrQcbOkC/mo22VPmqkmuI6M45+2POcXc6cusNNJMKJsKuRTqRTFtHUBB23c5Uusm9ti/tPBI0jLJD/ZGO91SHtdyHy4HkCbsC1z8y1UlzU02CpeL10zg3uY4a0DaYnTEnKxEI5TwYsrr6gE1sPh0tZb+0BQGUMsJfR09rCortv8=,iv:g6XYqRXVv47Z/onZEqpVxGpg7cY4AurHBsY/fuMIAAY=,tag:XAds23sdwoziXUb1CCtD7A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
