version: '3'
services:
  # ---- umami ----
  umami-postgres:
    image: postgres:17.9-alpine
    container_name: umami-postgres
    restart: always
    env_file:
      - .env.app.umami
    ports:
      - 5432:5432
    volumes:
      - /opt/umami/db:/var/lib/postgresql/data
  umami:
    image: ghcr.io/umami-software/umami:3.0.3
    container_name: umami
    restart: always
    env_file:
      - .env.app.umami
  # ---- caddy ----
  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile.gcp:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
volumes:
  caddy_data:
