services:
  error-pages:
    image: tarampampam/error-pages:3.8.0
    container_name: error-pages
    environment:
      - TEMPLATE_NAME=l7
    ports:
      - 8081:8080
    restart: always
    networks:
      - error-pages
  warpgate:
    image: ghcr.io/warp-tech/warpgate:0.16 # 0.17 borks on openssh v10
    container_name: warpgate
    ports:
      - 2222:2222 # ssh
      - 8888:8888 # http
      - 33306:33306 # mysql
      - 55432:55432 # postgres
    volumes:
      - /opt/warpgate/data:/data
    stdin_open: true
    tty: true
    restart: always
    networks:
      - warpgate
  # ---- rustdesk ----
  # # <https://rustdesk.com/docs/en/self-host/rustdesk-server-oss/docker/>
  # # need to open tcp/udp for 21114-21119
  hbbs:
    container_name: rustdesk-hbbs
    image: rustdesk/rustdesk-server:1.1.15
    command: hbbs
    environment:
      RELAY: hbbr:21117
    ports:
      - 21115:21115 # NAT test
      - 21116:21116 # connection service
      - 21116:21116/udp # connection service
      - 21118:21118 # web client
    volumes:
      - /opt/rustdesk/data:/root
    depends_on:
      - hbbr
    restart: always
    networks:
      - rustdesk
  hbbr:
    container_name: rustdesk-hbbr
    image: rustdesk/rustdesk-server:1.1.15
    command: hbbr
    ports:
      - 21117:21117 # relay
      - 21119:21119 # web client
    volumes:
      - /opt/rustdesk/data:/root
    restart: always
    networks:
      - rustdesk
networks:
  error-pages:
    driver: bridge
  warpgate:
    driver: bridge
  rustdesk:
    driver: bridge
