services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    pull_policy: always
    volumes:
      - /opt/open-webui:/app/backend/data
    ports:
      - 3000:8080
    env_file:
      - .env.app.open-webui
    restart: unless-stopped
    networks:
      - genai
networks:
  genai:
    driver: bridge
