services:
  error-pages:
    image: tarampampam/error-pages:3.7.1
    container_name: error-pages
    environment:
      - TEMPLATE_NAME=l7
    ports:
      - 8081:8080
    restart: always
    networks:
      - error-pages
  warpgate:
    image: ghcr.io/warp-tech/warpgate:0.16 # 0.17 borks on openssh v10
    container_name: warpgate
    ports:
      - 2222:2222 # ssh
      - 8888:8888 # http
      - 33306:33306 # mysql
      - 55432:55432 # postgres
    volumes:
      - /opt/warpgate/data:/data
    stdin_open: true
    tty: true
    restart: always
    networks:
      - warpgate
  syncthing:
    image: linuxserver/syncthing:2.0.11
    container_name: syncthing
    environment:
      PUID: 0
      PGID: 0
      TZ: Asia/Bangkok
      UMASK_SET: <022>
    volumes:
      - /home/ubuntu/Apps:/data/Apps
      - /opt/syncthing/config:/config
      - /opt/syncthing/:/data
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    restart: always
    networks:
      - syncthing
  # ---- rustdesk ----
  # # <https://rustdesk.com/docs/en/self-host/rustdesk-server-oss/docker/>
  # # need to open tcp/udp for 21114-21119
  # # host network mode - I guess this is to make hbbs and hbbr easier to communicate
  hbbs:
    container_name: rustdesk-hbbs
    image: rustdesk/rustdesk-server:1.1.14
    command: hbbs
    ports:
      - 21115:21115 # NAT test
      - 21116:21116 # connection service
      - 21118:21118 # web client
    volumes:
      - /opt/rustdesk/data:/root
    depends_on:
      - hbbr
    restart: always
    network_mode: "host"
  hbbr:
    container_name: rustdesk-hbbr
    image: rustdesk/rustdesk-server:1.1.14
    command: hbbr
    ports:
      - 21117:21117 # relay
    volumes:
      - /opt/rustdesk/data:/root
    restart: always
    network_mode: "host"
networks:
  error-pages:
    driver: bridge
  warpgate:
    driver: bridge
  syncthing:
    driver: bridge
