WAQI_API_KEY: ENC[AES256_GCM,data:g6etcjucIGHnrvs5EANSIsVc/Nz18Ey20JL/vOHRe/Oy2R/FP+RO3w==,iv:eTABWjj0S+L3Gt7iQNsPsjd9ti1yvSp2wwdUAsS+jnw=,tag:oiNqEEXRGHN4J0ddQew1Rg==,type:str]
DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:L4t3L1J/hkd+lK2/T8moPc1YEIfwIE2ipkNQloWtZBtDvzwh6oH34OI7sonHTU1w8T15hX1gM4IXOK6yNAan3EolPcduFv8E6+IaWQbb1wv3MDuoZXtZU2IuCY3IR3nES/G213OeW2it/opHjyTszqH/W0UILC9irg==,iv:23hPyZhGLR5I6U09yKHHHoSe/20SRNejSzy6kvvqXpQ=,tag:s9rdL/i8TVQwDlYCg7QPYw==,type:str]
TARGET_LATITUDE: ENC[AES256_GCM,data:HVovyuTjovZpgs1By83QItMh,iv:cUfm/nYUktC1/qJ8ZBpfwBabGHtVjSqo/p3+wvm8pIo=,tag:lysJqoVvEuRwV4sEoffq9w==,type:float]
TARGET_LONGITUDE: ENC[AES256_GCM,data:s9t9E5rjyuaSF2g47eCBJ0tO,iv:PoQSJHP08KpihUVV7VecxbGbVkOrkc8b/EUtToTQbmA=,tag:mdd2Vq4fAugnjVGJ0HS8Og==,type:float]
sops:
  age:
    - recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ekNIZ1BHT2tFNXQzSmpo
        ZHNYaXo0b3BkNGlYZjNFZzlpbURGY2IzeW40ClRncU1SSitMUGtHRk1LNWJvZEdy
        alVNVk9MdjEyZWt6Z1IzZ3JQelVMUk0KLS0tIEIrL05tcXhUNlNrNnJLQXpZUUdj
        eVpZcGFwcTBKbU8xNmN0dmJYT3ZMZ1UKBOMvmzo8Wzm5nIARVzSt9xdiUIKN1eRb
        cFTu8Tz1rgYICWBNucRKYjtGNrqTQESErK303kNmqiK2+moPmp+5mg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-16T16:03:04Z"
  mac: ENC[AES256_GCM,data:NJN8lsW2znlBv9lLmRTTGjb8cVV0Ax2k6h41mm3T/FXQyTTXvbSpdlZgihEy7NxZEYWSdFsH7+WmZT7r2AOrJCoGqWz2rUh4tC9h7Kc93gjwJpEECOGrDDPht1jcB8UzK9Og3IA/+c+iE3zX5+BA9DIAp09c5ZJfm3dfJPlhgiA=,iv:/O8J5d2Hd9dXrDDTy77x6uZZCIqOmwegFbUx+nhFtUg=,tag:PsCyifk5x7hxHWVHCZjLow==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
