ATUIN_DB_URI: ENC[AES256_GCM,data:Hx7HpY2gc+yvPN6qfIDMXXZMexRHnxGCNqMWHC+nGUYZAFKdhLlgOLn2KKIbf8SLy1eOlK/GOsso5BcuP3yIx74jE+jtBdNNJ/NwWky5MZI83D4H6azO8vIKfprg7g==,iv:2/pFVfO4+f9sLjaRV8T7QxyN8DKhoPcweAmoCxQgHZU=,tag:Fck3fRUI1V/2+ZP8y1Bu4g==,type:str]
sops:
  age:
    - recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZajRhS2dIOUNpTVk4bFBq
        bmM3eUdhbTZ6T0syVVJlSG9ZOW16QTdOZVNzCmx2SnlMeUdQQVBRUHZnUWtaRVJH
        cURoL3I5QmF4Z05vc2VadVYrSVNQWkUKLS0tIEtFM0JWbjd0Z0Q2bTBWbkFLMXNV
        UW9ERVNyZEN2bVBjSmUyTERNWE9jNFkKA0AvBEYu+tgirDGD9Z/YmaBdgbWwnltE
        clAfYOO0R6xFqJzhfZg7Bfwp98CrUZ47CjnpCBMFedMicqfAK0obTA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-05T13:20:30Z"
  mac: ENC[AES256_GCM,data:6Ucx8EYzJTv3KRPYqVtknfu//zkNmCB2msRKC+MEVQvqAz4m+V1bE2YkEqtdLEt8c7Hwv3mY88RU+xqE35sXl9w2vDkpP6klEdIn1fuhLoTPiFKKqTVpXNurMkLWgFl1Nm5tYueyLvfBp1TpGiPABX6aH2F1v+6XbGila2N5jkg=,iv:PWizI+p1zaSiTlgOLbkI8yZgHKKUkgkXJPdXeyk2ZYM=,tag:QPA6r9Hdlq0L0cXJyCnZ4w==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
