GITHUB_USERNAME: ENC[AES256_GCM,data:1mup74Wvb1w=,iv:HTEvOHef+7fZgm7W3oX1OmfFYeHcAePshE9qo79VCTA=,tag:kSFkJQMu6xyHyygkIMC6Rw==,type:str]
GITHUB_TOKEN: ENC[AES256_GCM,data:/gu6N6N76jq/p9ib2P3Ntj5nqDUkvO9rNvTs1xnk6ROOXDBOKZCbQg==,iv:oyO7JDdYj0gl/rJpBvRq2P+rvFVkuuGEkLKZKbEPpng=,tag:t/4ksoGP87srfy3xo1s3YQ==,type:str]
FORGEJO_TOKEN: ENC[AES256_GCM,data:X4kLRa7dE/rFw4zJ+iMBjU+2oY8nVF4ldp6nYQD5HTglspOQXeNmbA==,iv:O7+6e9qaqWSshfIZ1/8lLOofhZkSa6FEyzusDnGQSJI=,tag:VZVd0MFSyPXTRzgVP97taw==,type:str]
sops:
  age:
    - recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUVlJYnFnUzM5V1V3SWNE
        T2dzbkZCM1pEK3hNdzB4VUVzWUZHSGtLOURVCjVvMEc1VWIyemtweW9rVmJMMURw
        YUd4SXlpWXhHejJibGVzbTM2WU1DbzAKLS0tIDlIZUMrdk5EQkVabUJhUW9oZHZs
        N0JiemtTbldDOXF1YnZuTEJUSVFUd2cKq45XhNGZRvUKRgUS3xfxrpZW0FU8mI8J
        AFojW7MHOgzuGShYxz5BoK0D2yr89EI8IviB/M9m0CdEn54b6noiwA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-12T13:59:48Z"
  mac: ENC[AES256_GCM,data:OeqxM8tSLa9jsxdSmfbFP/alwrO6qam5bAmTFu4QYzrADNp9RVpr4jyLHzrztNsQzfwIuhqcLGk95OxQJL/q/RnKwnlrW/mWzvdCZyYutMc103oh12H3FtJTkXP5yo2BzDDFGeIZmVWUF82c76JQgU2W4LtjiKBeXRn9F4Irdaw=,iv:n7314r3x1Q5a3GRvapXm2khUecuCsTxc6NHq+tyLoWI=,tag:ZdVrZzGQVt5PgMhxB4vB8w==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
