GITSYNC_USERNAME: ENC[AES256_GCM,data:j6rCNcDC1Hw=,iv:f0dYi9bqzp48W8M5stqHJnalX4wL4wDogE9tocuwjhk=,tag:qPnkFJdQh+W4JjuiebM2xg==,type:str]
GITSYNC_PASSWORD: ENC[AES256_GCM,data:kaewhBYlZ1iEKY7PMWqhan/k6jQuWjRLwVX0QeYdVbEhXJvQCfmYCi0+rfxVTEYGsoyc9SR/8jFqKhTOoSYVB/Rmt+IPcmZGJ6zhiYiM1YP71WPC58+VP3JbQxgW,iv:ET2nprAerhwIoFXpMAO9XM9OvdMt/Qye1jjCB7qqsTU=,tag:WZz119IgC55JIjiftmyOhA==,type:str]
sops:
  age:
    - recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1a0tVZ2ZCR3FERDJYOGt2
        Z1BzS0RXaW9yOWpNZWo2anZIU2t6OTgrNlZRCmVJMUMreGQwQWxJZUcxRkMwWGkw
        eW9BWWR2VjJ4bE1nTnc5b1RYTnNuTlEKLS0tIDNGdzNwTjdJL0NLRWZyOVVqL2pK
        bFYvQkVkemRSdmhKSnAvcFQ3eEx6dXcKMMPrgzDdNbUBj0h0J9W4T3tbBEuIP1cx
        EGnzO1bKoiD4AceQeIwbbdgZCITDrcXKeJjTUC4b3hJfMhA7meMCOg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-28T09:18:01Z"
  mac: ENC[AES256_GCM,data:Q9fbTwWAQFmuQyRTudJqae/PBq90/faspBnI7he13nzqmWoJv8pITo6ujGv0HSaLaRi0PHGKni/mvcrEx2lnIhfj9G0QtaY2wdlqzfMVt03BbwHTGR+W65C9vXWYggPHeVaxX6UkNnr6aUrrlKRrhvieynkLVqoSWVIExQHTxh0=,iv:sxmvo38ed7R61aM+hqrVCdzJiBaQmL/EiwiSYbjmcyw=,tag:aqTgpmMnBTkTDfhBLQ3GpQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
