NTFY_BASE_URL: ENC[AES256_GCM,data:h+vrzJ6sXngmUka1trRLvZt3Ijql62ky,iv:ko4ygqPDxy7S58IX0qXVCVLK+dZAFbyEuNwIPHv16iQ=,tag:qDNNUHuetUdbWBC78MBrZw==,type:str]
sops:
  age:
    - recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZajRhS2dIOUNpTVk4bFBq
        bmM3eUdhbTZ6T0syVVJlSG9ZOW16QTdOZVNzCmx2SnlMeUdQQVBRUHZnUWtaRVJH
        cURoL3I5QmF4Z05vc2VadVYrSVNQWkUKLS0tIEtFM0JWbjd0Z0Q2bTBWbkFLMXNV
        UW9ERVNyZEN2bVBjSmUyTERNWE9jNFkKA0AvBEYu+tgirDGD9Z/YmaBdgbWwnltE
        clAfYOO0R6xFqJzhfZg7Bfwp98CrUZ47CjnpCBMFedMicqfAK0obTA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T07:20:50Z"
  mac: ENC[AES256_GCM,data:ieebuxvz0ajM33clINeRgzUXRO5f25Q0QaHHnXnqI6SWfUKk66IUNMzcu61YcwzpANbde+YBp7PdyD7xXX4S4M1yhRwxrrKLSUQ0zeb0vrHWkzmNlRkcGz1h/4jZy5VkOSROHuhaGrsFEMdGtjGTnhnBCj59VK7y+B5qr7Y/v7g=,iv:f1lyNosdMu6PQHU9R3RtkZ8SyoNdubSjjKuPBGNA7ak=,tag:B4qPpuZHcOkODa2fCPNTCg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
