WAKAPI_PASSWORD_SALT: ENC[AES256_GCM,data:Wh+ahnjaZBVu25xo4egsjPxZcMQUUheem4vBHDrBZxQ=,iv:draK+7rTI7v37xceU9qyoPP/Xm+ot6BN81sHKtMQaFg=,tag:7KJfrX9oGmsCAQAOoHqiug==,type:str]
WAKAPI_DB_NAME: ENC[AES256_GCM,data:Y3dGIn8k,iv:byza0smdh+D0ArzLhMSvlm4rLlzusJt1UMBO2fXl58I=,tag:t6yVO4eTfTsu/uovzJH42w==,type:str]
WAKAPI_DB_USER: ENC[AES256_GCM,data:RWO6E3FC,iv:ftFlak4E4lfdGykNqylhgBN0MehXtMYb0mo4haBAZOU=,tag:7p88vlZdkDn24obRpyjlYA==,type:str]
WAKAPI_DB_PASSWORD: ENC[AES256_GCM,data:eF1BvyhRqqWS+oRpKihUGttCWTPRuvzLyCXKDbPb/MY=,iv:YF9l31zmqeTCauRGWBgT8340ISpjTE0r0a35TF5Rf4Q=,tag:Klh/DjSJWVs4VZLO38y+8g==,type:str]
WAKAPI_MAIL_SENDER: ENC[AES256_GCM,data:hVWmcCc/+aCUidvXAILaCU4+,iv:xZi1o0LDWhU+T3TVduGILkdZj61CdMN15OdIbK9FjD4=,tag:wkaXaSraETNR+aTX94y4Hg==,type:str]
WAKAPI_MAIL_SMTP_HOST: ENC[AES256_GCM,data:kipvR89BJLwt5u1T4Gg8,iv:J/3kV2W1evlob/KhIRmqKPaUD3BgLfA1/sj58hyBboQ=,tag:XGh1L22iTELvBpe85by1aQ==,type:str]
WAKAPI_MAIL_SMTP_PORT: ENC[AES256_GCM,data:kl37,iv:Zfbzr/IrUd5UTLgRAHQha4tVw0ZUxZTxMm5QsW09UP8=,tag:pTyAytLjAyM1I2CZdPCBoA==,type:int]
WAKAPI_MAIL_SMTP_USER: ENC[AES256_GCM,data:Wfp7/pFF,iv:5dXn6h1zRxRWGLrNBrrZbh8+CUwcc36/+J37+omQq4A=,tag:I44DZFcmkhohE5Vb6owT0w==,type:str]
WAKAPI_MAIL_SMTP_PASS: ENC[AES256_GCM,data:br8ZyrBXSQnmqyQTqFTDcB7MhcS/4yXJ4SPBNv/2JuHN9Rhi,iv:yNWBCiRA3zuqzJ4abOK/zs7KbE9nVRZGKBgbtVQo1J4=,tag:6w6ld8/x6kaK5Ek3IiI6ow==,type:str]
WAKAPI_OIDC_ALLOW_SIGNUP: ENC[AES256_GCM,data:p4aR4A==,iv:Zfhmyxyvsfo9Abm2+gQWJQ5G/m1PdmSZcRfxutiNUn4=,tag:aL9KJzGDwKuW9z3gLkIVFQ==,type:bool]
WAKAPI_OIDC_PROVIDERS_0_NAME: ENC[AES256_GCM,data:GlRagEDsBsRV,iv:WUWcDuQo+T7+OAciQrCPptlYjijlRfaTIEx1iTsr9b8=,tag:JkHjo/1PYv7PDNvqWM1kiA==,type:str]
WAKAPI_OIDC_PROVIDERS_0_DISPLAY_NAME: ENC[AES256_GCM,data:GbyVlR8ea/ne,iv:CQEo3HrstqedXV+XanJTa0mAkVxU7nPAkh+1lpPS9Rs=,tag:FQbwPGp7NhmpUGXqAvWrNw==,type:str]
WAKAPI_OIDC_PROVIDERS_0_CLIENT_ID: ENC[AES256_GCM,data:HzOb1pH/r1vlNDBsOTeT4q2EbpzUWqyIxYx6crWh6WYo6zpU2B7fdw==,iv:9ZdKqhA5WvTw1Uf/Hj4MjEdOdLlMthK1DaGU94Ib8Jo=,tag:e4L3c+HnETEndhzm9ARYCA==,type:str]
WAKAPI_OIDC_PROVIDERS_0_CLIENT_SECRET: ENC[AES256_GCM,data:SeeBt9Gi5HU6r2oJuDAegKHCgGCC9LQ9WsJhFz6U6YTrylIqic+0LJPFJG4+E0qEQ4P9yJ3qq4dxXpPJZI0wtFY/0IZUp1kSyfCxLB4J1w8D3JGL3W0vXTGbA6mwtaOOAKa6j/17qj54VFLbc65UCAsFhXXLbSLT3eCmy2+yX6g=,iv:37uKMz6lTX5CNDbqIrFAslewoKzGhP8OhwaelJmhaLc=,tag:8rT0/lkGNOJz8/L3HWieMw==,type:str]
WAKAPI_OIDC_PROVIDERS_0_ENDPOINT: ENC[AES256_GCM,data:5aNY5q+DacfjS+OLv7MOtyo8g+CPg6B9aPXqP/t+EPTQNgd7bLBCm2kmdSGJaq8pdkKO,iv:LxkClBKxGVvR4gIrvQ56hxnAx39400zzrKQp8yBrABI=,tag:56qNslXXuead0J6bhDFb7g==,type:str]
sops:
  age:
    - recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNHFvWmJ3NWVHQ0JZaDh0
        bVhMc3ArSW9aVzE5L3hJRlN0M1MxOEFNRFY4Ckpsb2R4cG02OHl5NmNzNVJLQWpw
        a3EvaGxDa1hHK1lMbEpFUmlTMEJMNEEKLS0tIGpkSWNSUzhacWk1YUpKenVzdm5F
        d0ZaaHl3d25GWEtkMm5zS093MCtxQmcKMCLRNmO+94LwIEbn2UUPnrPrdSfPQAOM
        epiZufTAhAdhQxZJ4IZ9q7EPeWx4fIJdSUXIt7aoGkQ4MOPCFgX6vg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-23T07:48:49Z"
  mac: ENC[AES256_GCM,data:nE9EEpxDfBlzzb58tg94h5+juwhz/T9N/JVYLrwwF8x3fMayeZKR4K3StlpircrpQgG7Q6CT11BwM9qlbHCwCPRGgysu3nmc28FxonRUfXcFxU5GUBdWHo1+x1t5a+FX33DocIGIOVhvb89uDmr4ThBp7WTuFC11ns4ilBQXT2U=,iv:uQ+069uTE0Ilbfekt/t5tiwPXCO83+FLzivljMtqu3Q=,tag:0JL47LH6qjWLf+XGL2idKA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
