# maintenance: run `TRUNCATE TABLE sessions;`
kind: StatefulSet
name: miniflux-postgres
replicaCount: 1
containers:
  ## init
  # docker-compose up db
  # docker-compose up miniflux

  ## restore
  # start db container first, pg_restore and reset admin password
  ## pg_restore --user miniflux --dbname miniflux $BACKUP_FILE
  - name: postgres
    repository: postgres
    tag: 16.11-alpine
    port: 5432
    livenessProbeScheme: tcp
    envFrom:
      - secretRef:
          name: miniflux-postgres
    volumeMounts:
      - name: miniflux-data
        mountPath: /var/lib/postgresql/data
service:
  port: 5432
volumes:
  - name: miniflux-data
    hostPath:
      path: /opt/miniflux/db
