name: thai-tech-cal
containers:
  - name: thai-tech-cal
    repository: ghcr.io/kahnwong/ical-to-rss
    tag: "f4269ba"
    port: 3000
    env:
      - name: ICAL_URL
        value: "https://calendar.google.com/calendar/ical/tech.cal.th@gmail.com/public/basic.ics"
      - name: FEED_TITLE
        value: "รวม อัพเดท Tech event, Tech Meetup ในไทยไว้ในที่เดียว"
      - name: FEED_DESCRIPTION
        value: ""
      - name: FEED_AUTHOR_NAME
        value: "creatorsgarten"
      - name: FEED_AUTHOR_EMAIL
        value: ""
      - name: MODE
        value: "PRODUCTION"
