kind: StatefulSet
name: wallabag-redis
replicaCount: 1
containers:
  - name: redis
    repository: redis
    tag: 8.4.0-alpine
    port: 6379
    livenessProbeScheme: tcp
    envFrom:
      - secretRef:
          name: wallabag-redis
service:
  port: 6379
