kind: Deployment
name: immich
replicaCount: 1
containers:
  - name: immich-server
    repository: ghcr.io/immich-app/immich-server
    tag: v2.5.6
    port: 2283
    envFrom:
      - secretRef:
          name: immich
    volumeMounts:
      - name: immich-upload
        mountPath: /usr/src/app/upload
volumes:
  - name: immich-upload
    hostPath:
      path: /opt/immich/upload
service:
  port: 2283
  nodePort: 30030
