name: backup-miniflux
schedule: "2 0 * * *"
containers:
  - name: backup-miniflux
    repository: ghcr.io/kahnwong/docker-aws-backup
    tag: b686665
    env:
      - name: MODE
        value: DB_POSTGRES
      - name: SERVICE_NAME
        value: miniflux
      - name: POSTGRES_USERNAME
        valueFrom:
          secretKeyRef:
            name: miniflux-postgres
            key: POSTGRES_USER
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: miniflux-postgres
            key: POSTGRES_PASSWORD
      - name: POSTGRES_HOSTNAME
        value: miniflux-postgres.news.svc.cluster.local
    envFrom:
      - secretRef:
          name: backup
