name: backup-wallabag-content
schedule: "0 23 1 * *"
containers:
  - name: backup-wallabag-content
    repository: ghcr.io/kahnwong/docker-aws-backup
    tag: 07ea217
    env:
      - name: MODE
        value: ARCHIVE
      - name: SERVICE_NAME
        value: wallabag
      - name: BACKUP_PATH
        value: /opt/wallabag/images
      - name: BUCKET_NAME
        value: backup-monthly
    envFrom:
      - secretRef:
          name: backup
    volumeMounts:
      - name: wallabag
        mountPath: /opt/wallabag
volumes:
  - name: wallabag
    hostPath:
      path: /opt/wallabag
