name: backup-forgejo-data
schedule: "0 22 1 * *"
containers:
  - name: backup-forgejo-data
    repository: ghcr.io/kahnwong/docker-aws-backup
    tag: b46d44d
    env:
      - name: MODE
        value: ARCHIVE
      - name: SERVICE_NAME
        value: forgejo-data
      - name: BACKUP_PATH
        value: /opt/forgejo/data
      - name: BUCKET_NAME
        value: backup-monthly
    envFrom:
      - secretRef:
          name: backup
    volumeMounts:
      - name: forgejo
        mountPath: /opt/forgejo/data
volumes:
  - name: forgejo
    hostPath:
      path: /opt/forgejo/data
