name: maintenance-backup-monthly-prune
schedule: "5 0 * * *"
containers:
  - name: maintenance-backup-monthly-prune
    repository: ghcr.io/kahnwong/docker-aws-backup
    tag: b46d44d
    command: ["sh", "-c"]
    args:
      - |
        current_date=$(date +%Y-%m-%d)
        remove_backup_before_date=$(date +%Y-%m-%d -d "1 month ago")
        aws s3api list-objects-v2 \
          --endpoint-url "$S3_ENDPOINT" \
          --bucket "backup-monthly" \
          --output text \
          --query "Contents[?LastModified<= '$remove_backup_before_date'].[Key]" | xargs printf -- "s3://backup-monthly/%s\n" | xargs -L 1 aws s3 rm --endpoint-url "$S3_ENDPOINT"
    envFrom:
      - secretRef:
          name: backup
