name: water-cut-notify
schedule: "0 */6 * * *"
containers:
  - name: water-cut-notify
    repository: ghcr.io/kahnwong/water-cut-notify
    tag: "1327352"
    envFrom:
      - secretRef:
          name: water-cut-notify
imagePullSecrets:
  - name: ghcr-cfg
