kind: ENC[AES256_GCM,data:FJqt9NEUC9fz6A==,iv:ZtORw8vRLeyZpbyJOsnoywfqf9QGbPKBgva/sXxlye4=,tag:TJiexjTrMSRCSXyNLfGKVA==,type:str]
name: ENC[AES256_GCM,data:opC4zvI=,iv:RLNj2RCFJvsfN7kzCMOxltKSgF6BM1kjP9M9bAC8n0Q=,tag:uxQJhi4WD8OI9mN2LXfEDQ==,type:str]
replicaCount: ENC[AES256_GCM,data:+Q==,iv:AozqFNCOD1UNB3QKC80IBAyyg8+MEjWqYk/gBGbFfc0=,tag:c3By7uXjIY7QSsww/pLN3g==,type:int]
containers:
  - name: ENC[AES256_GCM,data:Ke9BbwM=,iv:I8mVczAZQlzGRTxrpDFWXXNSbuSS6jAxhst8tO9RodI=,tag:FbhMKaJyBcsbY32XCccINQ==,type:str]
    repository: ENC[AES256_GCM,data:BlC4vwQCg2K7j5AXF+o=,iv:v1VujH8xRT7XinRU1BfQ9jTCP5pvMijkyQRcC/f1Bdk=,tag:fI7WPyveePatgaNcba1hnA==,type:str]
    tag: ENC[AES256_GCM,data:0nuWiFn6,iv:KyuZ+xfus6I8Wp/gXP4SGoR3APgkY6Ym15TIgXCCVQ4=,tag:7Uc6JyTdVPA5zDBHffaKfA==,type:str]
    port: ENC[AES256_GCM,data:0h5zYg==,iv:RKBFSJZB4tTdHjAZBVhggUMtYHtfCh9XPE3jOF6rROk=,tag:FKd7m74PUPEToBVnVaQtPg==,type:int]
    env:
      - name: ENC[AES256_GCM,data:zBn6PWryYUXM5vI=,iv:NQzRGxu8FHMESSdZIConhcG0G+1A9eg7BPGkM8SrbRQ=,tag:l3OT8RMpoBGJUbDZ4tAeCg==,type:str]
        value: ENC[AES256_GCM,data:MRGSlZ34,iv:8/oxnQSFfYtxJdLRl/TZMEModxI608z8PIXMFCaaO4I=,tag:L6pbf2u8aaAerukiKdhnaw==,type:str]
      - name: ENC[AES256_GCM,data:ql9gl+aHQSrSPkdMC5fN,iv:4QevT9Y6UWb99TxMOy8v6vvQju1H6dcP5uGdIZbr9xA=,tag:/XW7P9Jb880kUFZg0eZFGw==,type:str]
        value: ENC[AES256_GCM,data:isuAgE6DiqLxA1A=,iv:BIZJQmr5ZJXD6arZP/WGcGRl0llzL8VkZUYqm0S9YPU=,tag:ib6IcGk8dSEoutM5OLhNBQ==,type:str]
      - name: ENC[AES256_GCM,data:vQzPaqQaAPjSM3V70k8=,iv:QljgRXoa6/IeUcz6kI9hY2jmFOoe8AatgAvHv8WbQN0=,tag:bnIGmV8T8sBQvBTC3lKn1g==,type:str]
        value: ENC[AES256_GCM,data:uIJaWe3RRIbMmA==,iv:1fTvpUlW3qTmdzHhOg2aT6NMThXtXA2NKbU02kktt1s=,tag:+TdA9g9/Q2ugjy9qJuFNXg==,type:str]
      - name: ENC[AES256_GCM,data:hfNIf5zmMTbk6BQ=,iv:lR/SkpIUlPLyj7RIvFyAHjw8KNqdkF53dSDUByBd9m4=,tag:KVUiAu+N7XAzo4yh/cZAow==,type:str]
        value: ENC[AES256_GCM,data:PI6JJFM+Dw==,iv:6/4UXH1fwd7/kKXlZoWW6T75bS7idoiKBslqRCMWb3c=,tag:7q2ys4CyqhDUf2oebW9k5g==,type:str]
    volumeMounts:
      - name: ENC[AES256_GCM,data:jTPwI7o6,iv:PfnvA+iOb/V0JnIcNHngPSqiJjl7dbBkFnDyod0b4Ek=,tag:HOCY6Y5nkfcCqA3CvhAWUg==,type:str]
        mountPath: ENC[AES256_GCM,data:lpM9nnARj+QpPFw6,iv:Rp5DAp8iGUEhoaM0EppgOz2FEuCX5/3Y+3iq/HZR8os=,tag:QgUfnjtn7jGI6Uq4uiq39g==,type:str]
      - name: ENC[AES256_GCM,data:bfKZBg==,iv:B4diaWoKqhiktbaPRjeAC6PnQiWIC6zaECNxNvEBiVs=,tag:T+0lk933C+u1aNeFuY50kA==,type:str]
        mountPath: ENC[AES256_GCM,data:FBrI/fI=,iv:Fu/tQ8NzGBF3VvxV43H+iwtrZshfWS9NjoyR7tmbqOg=,tag:QvvbRLWVBOt0Hp2G7sDr8A==,type:str]
      - name: ENC[AES256_GCM,data:OqFK1IpZQFs=,iv:SRP3eA3ynuld2QgTTg+Qsl6BOsyJowAfvFRKf478DFI=,tag:BLjhnt6Jaq6cPkxyWx17WA==,type:str]
        mountPath: ENC[AES256_GCM,data:K/faK+MBXo2O,iv:mkrhippCAfgToY4P1VtAIm4Enu3iuCZ3LyxvQAWw7Uo=,tag:bq1x6Gqfq3IZ5wxVUQ0g3g==,type:str]
      - name: ENC[AES256_GCM,data:wurows4=,iv:Xtt1pd68vpthemmBHJZU8VWKxQHUqRrYJdbrJ25V6MQ=,tag:1M92EAYBWUfnrauoX3QRVg==,type:str]
        mountPath: ENC[AES256_GCM,data:3HSTBmPK,iv:MvhLvHYUp1g0mQyJKMbw8Mw2UV2Ufnk6lYF1xTh/Zao=,tag:X2eBIfNjWe4hod8zSDsoAg==,type:str]
      - name: ENC[AES256_GCM,data:AKBlC5A=,iv:5XiQngq9JSsW2UP++xnUfNh1YFFB4dc/o5TTJ2kmt7E=,tag:tGU116G6ZDQ4LY4lccEptg==,type:str]
        mountPath: ENC[AES256_GCM,data:rf8CtGWS,iv:6hpMfiy/egjeuMJOylFErpFETPurv6KseBlUjjwdOuA=,tag:4BHqXhQBdibqniAJanlnuQ==,type:str]
      - name: ENC[AES256_GCM,data:XHTL0oyPFp55,iv:fLhJMfruxFVbhCyVRNK0D7iFSzuTKJygh60huo+incY=,tag:ur8W0ia/GNZSy0dTyTzxFA==,type:str]
        mountPath: ENC[AES256_GCM,data:MWPZFR+/I/T1lw==,iv:8n9gFl1ZwafNemudhJoJRJruMASxD2iuCji2I5my8RQ=,tag:NM3AxJqtaASFA6jmHrbNDw==,type:str]
volumes:
  - name: ENC[AES256_GCM,data:UYIfGvD+,iv:jFO0BbKuwYrdxhQl+ws9KDYhrQuWaMtqmzuR3rBGx4s=,tag:2gmWmBPyiAC2WVFQk1eRRQ==,type:str]
    hostPath:
      path: ENC[AES256_GCM,data:tlS2x4PLv26IJnqxaNog0E8=,iv:QtypGJYR3kSROi0dFi16TN2Gkw5/47QYFwHjQsC+P9I=,tag:EDE176AJSD4IzO8JlMbo+g==,type:str]
  - name: ENC[AES256_GCM,data:4TzmxA==,iv:LYdXDOVm+ygQaqOExNfaQsty6pkjMNPJlGzc3P2SapU=,tag:meLIEGwVaw9TPmrI2npVvA==,type:str]
    hostPath:
      path: ENC[AES256_GCM,data:9V9KF/q9PWGosAbbJ98l9e/pd0KdSd/lrWtnm/UzFRFMDJ0U08z3P/A=,iv:C/aqhnLHR838NBnezSl4R4LlQw5YO1hTi+gZWEfwyBM=,tag:75JRyezAE8TDd/rZh8cH5w==,type:str]
  - name: ENC[AES256_GCM,data:KeFoHSOiU10=,iv:Ca2UjRmJIlvOSsxYcUIslUYU1B+pIVeLxoglwKpC+D0=,tag:Gvc2tX6wTML9kIAyxcvPbQ==,type:str]
    hostPath:
      path: ENC[AES256_GCM,data:J7occte+3nX7eYVyNoClnifonQ==,iv:jhSnr8gXz0ITGIoAxLKXFL2uYImlKuFzJZZoy2TOxkc=,tag:BePh2WqylGXmQ2Y1aKXVOQ==,type:str]
  - name: ENC[AES256_GCM,data:Fg+OPy4=,iv:RULILBJLS48J74gvKEXjwtOymFGR5bozNh7/ZTUtLZU=,tag:XyGmuGEQkRMMXZN3PksIAA==,type:str]
    hostPath:
      path: ENC[AES256_GCM,data:iE7GMyQhiiCweQYZWRHtOQ==,iv:KCj4qUsvVIYaOLEmS1Ys+foy7HJNuP/VMpBENrWddOc=,tag:l57lPrdYbkx814pvN0NQaA==,type:str]
  - name: ENC[AES256_GCM,data:aVY/NOQ=,iv:BHIY5qq8t/hDjTBF5jwWwhVVzrpkefY3S9UnZnH2Gl4=,tag:ZXyeshmA30huheSSfQ98LQ==,type:str]
    hostPath:
      path: ENC[AES256_GCM,data:ugLf512F2g6f5ggD7r81fA==,iv:fvcz6soRXyfFJ4ltlYoZu5y8n33EnitPMcePXXhSyI8=,tag:jnA+IKs6avb7T9CY4utxeg==,type:str]
  - name: ENC[AES256_GCM,data:ufWOzv83tvt8,iv:HGEFdMd/pJtezc1UR4EaqPKawUkAB7aFrrMh49wxDgo=,tag:KY3WyWC84ZcaKQG2VAyLJw==,type:str]
    hostPath:
      path: ENC[AES256_GCM,data:XfDehxCTNcDfU62KQs4r/1fKD6k=,iv:c66g5p7Qc+zzQTEWKTIRS0CHkgiP6x52nsnyb5eGpgo=,tag:1fGtZeHpX4qkE4v7I39w9g==,type:str]
service:
  port: ENC[AES256_GCM,data:ItCu2Q==,iv:mzlnJisOEnN2WgEsLwYFEDlFGq1JjKz7VQWTLaIqspY=,tag:Zb3JwrDHol0fLmXLldf3Vg==,type:int]
  nodePort: ENC[AES256_GCM,data:dnhGaek=,iv:V5giXK/D4lED1YnWv3XxXsR3VW2yd9TADT/kET8Lofs=,tag:4khekM1ZoLtINCvfhGzbtw==,type:int]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14ke6m4zzfpgpu2herm8cu22wshyalyfkvjp2hjedm34h7wg0ypjss9e3ct
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLR0hJZDlWYWxZK3dEQXlp
        WUxOUkNDWUg1N1AyREJKL0R1ZzNzS2tSTEhjCm5SU0dtWGhiNW9pL1ZIbU1BYjdw
        b05FQVFyZkhmbkk5bWhlc3laK1BJK2cKLS0tIFBGRE9BYnp5OVVJTStQUVhIeUhF
        RFdIUmlrRGhxalcxTWF2dUIrYnRlZDgKDwTzh0GwJJQcpNkXlLICr+dSWheb2c3X
        LyH9A3NMH+lALYON4fTLWjfkKKa8VxWETohIhFjntTuP9NIFgavegA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-07-10T10:23:01Z"
  mac: ENC[AES256_GCM,data:g6IBiUYmpMzrKYqdAghCxqCxel8HB472OyKen7aOKtwDe/WALmnwaqjy0zcCQcvGbRXXb5cLh/LG9jhhWtd/dr4wQ7npRpsZlwIUyu6SjCNzqadsojgJvcPUZwaQFcgsrYKt4Oag6QNNE0niFRvl3mcmz8Ujo+xsyHGZeMwsn6o=,iv:JPTvkzI4NIVNJy/ZJXeQLfYmEj88V21G5gwzSMgk6S4=,tag:epuXMkQwI4Vjq6X8xsqtmQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
